### ISSUE TITLE
Feature Request: Location Message Attachment

### ISSUE THREAD

**Issue by Saijin-Naib** [moezbhatti/qksms#1614] opened 2020-05-22 01:10 UTC
### DESCRIPTION
I'd love to see the ability to attach a location to the message.

How I envision this working:
User can set (optional) providers such as Google/Bing/OSM to provide the location encoded into a clickable link.

If a provider is chosen, then a static image of the location will also be attached to the message alongside the link and in-line information below.

The location attachment request will also in-line in text the LAT/LON at minimum.

**Comment by moezbhatti** [comment] 2021-01-02 04:18
Duplicate of #709

**Closed by moezbhatti** 2021-01-02 04:18 UTC
