### ISSUE TITLE
Contact pop-up opened by contact icon

### ISSUE THREAD

**Issue by f380cedric** [moezbhatti/qksms#518] opened 2016-06-08 13:39 UTC
### DESCRIPTION

Open contact information from the contact icon
### STEPS
1. Click on the icon contact (in QKSM home or in conversation)
2. Click outside of the pop-up or on the android return button
3. Now, for example, try to open another contact
### OBSERVATIONS

Click outside of the contact pop-up makes QKSMS buggy until you do not close it (or stop focusing the app).Sometimes, when you use the return button to exit the app, contact pop-up appears

**Comment by sm4rk0** [comment] 2016-06-08 14:16
Can't reproduce.
Does it happen every time for you?
What QKSMS version are you using?
Can you describe the buggy behavior?

**Comment by f380cedric** [comment] 2016-06-08 14:44
Yes, every time. The last on Google Play (2.5.5). I cannot open another one, when I open a conversation, I do not have the conversation  but only the bar to write sms, when I click on unregistered contact icon, sometimes pop-up appears.

**Comment by sm4rk0** [comment] 2016-06-08 15:02
OK, I'm testing version 2.6.1. I thought it's already released...
If you'd like to try it, join the Google+ community and follow the instructions there:
https://plus.google.com/communities/104505769539048913485

**Comment by f380cedric** [comment] 2016-06-08 15:17
Hum, exactly the same on 2.6.1. The only difference is that "Sometimes, when you use the return button to exit the app, contact pop-up appears"  becomes  "sometimes, when you use the return button to exit the app and reopen it, contact pop-up appears"

**Comment by moezbhatti** [comment] 2016-07-04 04:00
Can't seem to reproduce this one

**Comment by f380cedric** [comment] 2016-07-14 11:26
It seems to affect phones with EMUI (Huawei/Honor). Issu on Honor 7 (mine) and Huawei P8 lite (not mine). Maybe it is an issue with the contact manager used by EMUI (Camcard)

**Comment by moezbhatti** [comment] 2018-01-13 06:02
Should be fixed in QKSMS 3.0

If it happens again, let me know and I'll reopen

**Closed by moezbhatti** 2018-01-13 06:02 UTC
Labels: Bug: Needs Repro
