### ISSUE TITLE
[Request] Random material colors for each contact

### ISSUE THREAD

**Issue by NitroCipher** [moezbhatti/qksms#1309] opened 2018-09-20 20:30 UTC
I switched over to this app after Android Messages destroyed itself, and I miss the random color themes that were assigned to each contact. It made it extremely easy to differentiate between contacts. Please add this!

**Comment by mddvul22** [comment] 2019-09-13 17:58
Yes, please.  A single color makes the contacts very hard to differentiate and makes the app less user-friendly.  I'm not requesting that it be the default setting, but please let it be an option.

**Comment by NitroCipher** [comment] 2019-12-16 15:47
Woah, i just randomly came to this issue to see if there was anything said about it recently. And i was greated by "Release 3.8"! Thanks man!

**Comment by moezbhatti** [comment] 2019-12-16 16:32
I'll be implementing it this week!

**Comment by moezbhatti** [comment] 2019-12-27 05:33
Duplicate of #133

**Closed by moezbhatti** 2019-12-27 05:33 UTC

**Comment by StefanBrand** [comment] 2020-06-19 13:10
Has this been implemented? Where is the relevant commit? I'd like to have this downstreamed to /e/ foundations SMS app. :)
