### ISSUE TITLE
Wrong not GSM 7bit messages size indicator

### ISSUE THREAD

**Issue by billic** [moezbhatti/qksms#446] opened 2016-03-17 19:00 UTC
### DESCRIPTION
Typing message length indicator doesn't know about codepage inside SMS: [wikipedia](https://en.wikipedia.org/wiki/GSM_03.38) says about three variants: 7bit (160 chars per message), 8bit (?) and UCS-2 (70 chars per message -- my option)

### STEPS
1. Turn character counter on
2. Type long enough message with national symbols from UCS-2

### EXPECTED
the counter should show the number of remaining characters in the message depending on the encoding

### OBSERVATIONS
counter shows number of characters as they encoded by 7bit charset

example:
![s60317-214329](https://cloud.githubusercontent.com/assets/17784709/13857525/b49961de-ec93-11e5-8028-cdde06eec8ef.jpg)

**Comment by ememoho** [comment] 2016-08-07 20:52
I believe this is a duplicate of #94, so glad to see it is actually has the "confirmed" tag, since it clearly is not an "enhancement" request.

**Comment by moezbhatti** [comment] 2016-08-27 05:38
I'll close this one then, and update the other label. Thanks for pointing that out

**Closed by moezbhatti** 2016-08-27 05:38 UTC
Labels: bug: confirmed repro
