### ISSUE TITLE
Battery drain/wakelock from MMS

### ISSUE THREAD

**Issue by tomose** [moezbhatti/qksms#456] opened 2016-03-24 11:58 UTC
Android 5.1.1 (stock Nexus6)
QKSMS 2.5.4

http://imgur.com/a/H4YpD

Not sure what exactly is causing it but I've included screenshots of:
1. Battery stats page
2. Detailed battery stats for QKSMS
3. App Info
4. WLD info page showing MMS Connectivity being the culprit
5. MMS settings page

I can't be certain of when this started. I don't pay too close attention to these things and just happened to notice that QKSMS was riding pretty high on the battery usage when I happened to look today. I get MMS messages just fine and rarely ever send them myself but I have had ZERO issues sending or receiving MMS. I'm on wifi usually.

Things I will try in the mean time while you look into the issue...
1. Disable AFWall
2. Reset all QKSMS settings and user data

Beyond that, I don't know what else externally would be affecting it.

**Comment by moezbhatti** [comment] 2016-04-04 01:01
I can't seem to reproduce this, anyone else?

**Comment by woj-tek** [comment] 2016-08-03 15:54
Just encoutered it a while back, while searching noticed there was two thread (v. #344, but this one seems to have more info).

Have same observation, WLD reporting "MMS Connectivity" as culprit.

Steps to reproduce - I was abroad for a week and because of that I very rarely used mobile data connectivity - usually turn on, check the mail/directions, disable mobile data. Probably in thea meantime QKSMS received notification that there is a pending MMS and tried to download it, but it failed, and then somehow entered in a loop to download it, but because the mobile data was disabled in was constantly failing (sorry, no logcat, just guesses, didn't have my computer with me). Forcing stop didn't help, I had to freeze QKSMS with titanium backup to revive phone to a usable state because without it went dead within hours instead of lasting 2 days).

I usually don't use MMS and after I got back home and I restored QKSMS the message was finally retrieved.

**Comment by tomasz1986** [comment] 2016-11-08 03:28
I have experienced this wakelock just today. It happened at night when I had mobile data completely disabled in system settings. It seems that QKSMS kept trying to download the message despite no active data connection. The wakelock kept going on even though the data connection was available later.

**Comment by Flavien06** [comment] 2016-11-13 04:20
I think have the same problem with qksms 2.7.3
(I migrate from Signal to Qksms 1 week ago) 
http://m.imgur.com/TaSQa00
My data is always off. I active only for mms.
Nexus 4, Rom Chroma  6.0.1

**Comment by moezbhatti** [comment] 2017-10-04 03:55
Should be fixed in QKSMS 3.0

**Closed by moezbhatti** 2017-10-04 03:55 UTC
Labels: Bug: Needs Repro
