### ISSUE TITLE
Contact names not displayed

### ISSUE THREAD

**Issue by biff80** [moezbhatti/qksms#1418] opened 2019-04-24 20:09 UTC
### DESCRIPTION

Contacts are displayed by phone number only; doesn't recognize names (but it will display their contact photo)

### STEPS
Phone:  OnePlus5T (Hydrogen OS, 9.0.2)
1. Install QKSMS
2. Text someone

### EXPECTED
When I'm texting with someone, qksms should show the name of the contact and their photo.

### OBSERVATIONS
It seems like QKSMS only partially recognizes that the person is in my contact book.

**Comment by moezbhatti** [comment] 2019-04-24 20:12
What happens if you go into the app settings and hit the Sync messages button?

**Comment by biff80** [comment] 2019-04-30 07:18
I've tried previously to:
* switching to another sms program and switching back
* staying with qksms and hitting the resync button
* restarting the phone

QKSMS must recognize the contact because it's displaying their contact photo, but just won't display their names. There is even the "add to contacts" button next to their phone number, but when I click on it, the phone pulls up their contact info.

**Comment by paul1764** [comment] 2019-04-30 16:57
I have a similar issue
Description: QKSMS does not recognize newly added contacts, unless I re-sync with native sms database

Steps:
Phone: Motorola X4, Model number XT1900-1
OS: Android 9, build number PPW29.69-39-2

1. Instal QKSMS 3.6.4
2. Get a text from a number not in my contacts
3. Open the conversation
4. Touch 3-dot menu
5. Touch add contact button
6. Create new contact or add to existing
7. QKSMS still just shows the number, not the contact name
8. Name will be shown after re-syncing

Expected:
QKSMS should show contact names without re-syncing (which is somewhat time consuming)

Observations
Like @biff80, when I touch "add contact" after adding the number to a contact, that contact will be open, but QKSMS will not display the name.

**Comment by symphorien** [comment] 2019-08-25 14:11
I can confirm @paul1764 comment on LineageOS 14.1 (android 7) and QKSMS 3.6.6.

**Comment by moezbhatti** [comment] 2019-11-24 16:05
Are you still experiencing this issue on 3.7.9?

**Comment by paul1764** [comment] 2019-11-25 03:45
Sorry, I am still on 3.7.4 because I've been in a place where I can't update my phone for a few weeks. When I'm able to upgrade (in a couple months), I'll let you know.

**Comment by biff80** [comment] 2019-11-25 06:30
I have the F-droid version at 3.7.6. Tried to download the apk from GitHub but it failed to install; will attempt again later and update you.

**Comment by moezbhatti** [comment] 2019-11-25 06:34
Unfortunately the two builds aren't compatible with one another, so you'd have to uninstall the F-Droid version if you want to install the one from Github

**Comment by symphorien** [comment] 2019-11-25 20:39
3.7.6 (f-droid) seems to work fine here.

**Comment by adriffaud** [comment] 2019-11-30 10:26
I also have this bug on OP5T, with version 3.7.6 from F-Droid (fresh install).
What's strange is that it does not happen to all contacts, only some of them

**Comment by biff80** [comment] 2019-12-11 20:01
F-droid dropped version 3.7.10 today; same issue, unfortunately. What's strange is a few contacts will have their name listed, but 99% of them aren't recognized by name (though will still show their contact photos). Re-syncing and restarting the phone doesn't work.

**Comment by moezbhatti** [comment] 2019-12-11 20:12
Hmm, interesting. I'm curious to see what happens with the 3.8 release - I've made some pretty significant changes to the way that contacts are synced

**Comment by moezbhatti** [comment] 2020-01-14 01:45
Pretty sure this should be fixed in 3.8

**Closed by moezbhatti** 2020-01-14 01:45 UTC
Labels: bug

**Comment by jpodolski** [comment] 2022-05-22 21:55
Just happened to me about a week ago, and I haven't changed a thing about my contacts or SMS app. My phone powered up one day and no contacts will show. Contact colors have stayed, and group names remain, but nothing. Interestingly, it also happened to calls... So maybe not a QKSMS issue?

Recent LineageOS, Android 11 on Google Pixel 3 "blueline", QKSMS 3.9.2 downloaded from FDroid, using Simple Contacts 6.17.2.
