### ISSUE TITLE
Feature request: SMS reminder

### ISSUE THREAD

**Issue by OpenWarp** [moezbhatti/qksms#1648] opened 2020-09-23 20:46 UTC
I often receive my bank and doctor appointments via SMS with important details.
Rather than creating a calendar event, I would rather prefer to be able to set up a reminder to the message itself.
May I suggest a pop up menu item to quickly set a reminder to specific date and time on selected message(s). It would be nice to have the same option available for message notifications.

Expected behaviour:
1. SMS is received
2. Shall any of 3 notification buttons is configured as "Reminder" then there is an option to set up a reminder straight from notification area. Otherwise, open the message dialogue as usual.
3. Select a message by long press on it.
4. Press three dots menu in the top right-hand corner and observe the dialogue to copy text, forward, and set a reminder.
The option to set a reminder may not be available if multiple messages are selected.
5. Set up date and time for the reminder as usual
6. Done
7. At specific date and time the message(s) notification is to show up as if the message have just been received. There is no need to craft something fancy here. Having said that, the alarm style reminder will be great, with the ability to postpone notification.

**Comment by moezbhatti** [comment] 2020-12-13 07:14
Duplicate of #167

**Closed by moezbhatti** 2020-12-13 07:14 UTC
