### ISSUE TITLE
[Feature Requests] Pair Other Devices, Desktop Versions, Answer And Make Calls On Other Devices

### ISSUE THREAD

**Issue by trymeouteh** [moezbhatti/qksms#1356] opened 2018-12-29 01:59 UTC
QKSMS is the best Free, Open Source SMS app that is on F-Driod. I Like QKSMS since it allows me to have a nice SMS app on my phone which uses a custom ROM and is de-googled. I have three feature requests.

1. Please allow QKSMS to pair to other devices such as another Android Phone or an Android Tablet. It can work similar to how Signal Messenger pairs with other desktop devices. This will required the synced data to be encrypted during transit to ensure security and privacy.

2. Please create desktop version of QKSMS for Windows, Linux and Mac (Especially Linux). I would advise using Electron or something similar that is open source when creating QKSMS for desktop devices. For this to work the first feature request of pairing devices will need to be done. The one things that will be needed to be synced between desktop devices and the phone beside messages would be the Android contacts.

3. Please allow QKSMS to answer incoming calls and make outgoing calls. Its a dumb feature request on its own but with the first feature request of pairing devices it would be excellent to be able to make a call or answer a call on your Tablet or desktop device. Again this data in transit will need to be encrypted for security and privacy.

With these three feature requests this will allow users to send and receive text messages and manage calls on their phones, tablets, and computers and without using a phone with google dependencies. I know there are apps that do this already but none that I can find that are on F-Driod and are open source. I know PulseSMS is the closest thing out there but PulseSMS uses a cloud to sync your devices and even though PulseSMS is encrypted in transit and at rest it is kinda overkill and I think unnecessary since the text messages can only be sent and received from your phone with the SIM card.

I am aware of what I am asking for is nothing small or minor and if you do decide to take this on I am aware it could take months to be completed.

Thank you for such an amazing app. Keep up the amazing work!

**Comment by moezbhatti** [comment] 2018-12-29 23:59
Going to mark this as a duplicate of #818, since desktop messaging basically involves building a web-based messaging interface that can be used on any other platform

Regarding the phone call support, I don't think that this is something I'll end up supporting, as it adds an enormous amount of complexity to the project for something that I don't think most people need. Perhaps this might make more sense in the future if I've got more development manpower

**Closed by moezbhatti** 2018-12-29 23:59 UTC
