### ISSUE TITLE
Texting numbers that are not in contact

### ISSUE THREAD

**Issue by PrinceZavion** [moezbhatti/qksms#950] opened 2018-03-28 16:34 UTC
Issues start when I try to send a new message. The search bar won't allow me to and number, just letters.
1. Hit new message button in app
2. Try to add number to search bar at top of page.

**Comment by moezbhatti** [comment] 2018-03-28 16:37
Which version of the app are you using?

**Comment by PrinceZavion** [comment] 2018-03-28 16:42
3.0 Beta 7

**Comment by MyNameIsCosmo** [comment] 2018-03-28 16:44
I've had similar issues to this on Beta 7

On my LG G5, I can't use backspace when inputting a number/name in a new message, I need to select all and cut. I haven't tracked down if the issue is with my keyboard or with qksms.
In an AVD, using the `Nexus 5X API 25 x86`, when in a compose box, it will not let me type numbers, but will let me type letters. (Resolution states 420dpi)
In an AVD, using the `Pixel API 25 x86`, qksms works as expected. (Resolution states xxhdpi)

I haven't tested into this further.

**Comment by moezbhatti** [comment] 2018-03-28 16:44
When you type the number, it should show an empty contact with that number. Click that to add them as a recipient

**Comment by moezbhatti** [comment] 2018-03-28 16:45
Ah, interesting. I'll test this on the AVD. My bad - I assumed user error

**Comment by PrinceZavion** [comment] 2018-03-28 16:47
@moezbhatti it doesn't even allow me to add number to that search bar.

**Comment by moezbhatti** [comment] 2018-04-03 05:51
Fixed in 12001f70ac5040290490672e188ae56f8de3c0d4

**Closed by moezbhatti** 2018-04-03 05:51 UTC
Labels: Bug
