### ISSUE TITLE
Max messages per contact and global limiter - feature request.

### ISSUE THREAD

**Issue by cra3yk** [moezbhatti/qksms#1298] opened 2018-09-07 15:01 UTC
Hello

I politely ask for ability to set maximum messages per contact and globally.
When (for example) limit is 20 globally, then it applied for every contact in contact book, but user can change it in particular contact (for example one contact has 50)

How it works? When one contact has 20 messages and new message arrived - the oldest one will be deleted, so there will be always 20 last messages. For contact configured with 50 - it will be the last 50 available.

I'm using QKSMS in phone that receive sms'es from monitoring system - i receive 30-40 sms'es per day and it is hard to delete all of them but 5 last.
Ok - I can delete whole "sms thread", but it also delete settings like color, sms-tone etc. that I configured for this contact.

I remember that Messenger from Cyanogenmod has this feature, but it was long time ago (KitKat or JB)

I miss this feature so much!

**Comment by MyFirstChoiceWasTaken** [comment] 2019-06-18 08:34
+1 for this (in particular, the global limiter).

**Comment by moezbhatti** [comment] 2019-08-12 20:52
Duplicate of #119

**Closed by moezbhatti** 2019-08-12 20:52 UTC
