### ISSUE TITLE
Icon disapear from Launcher

### ISSUE THREAD

**Issue by BHMath** [moezbhatti/qksms#141] opened 2015-08-18 20:37 UTC
Everytime I add the app icon to my launcher it disappears soon or later. This happens even if I drop it to the quick launch or to any screen. I use Google Launcher.

**Comment by hebertpalomino** [comment] 2015-08-19 20:37
Using Google Launcher as well. Can't seem to reproduce this.

**Comment by JonShepChen** [comment] 2015-08-20 07:13
I can't reproduce as well (using Google Launcher). What device and how long does it usually take before it disappears?

**Comment by BHMath** [comment] 2015-08-20 07:37
I'm using a Galaxy Nexus With CyanogenMod 11 Android 4.4.4. I know my girlfriend had the same problem with a S2 with cyanogenMod too.

I can't tell you how long. I can be two minutes or 3 days (for my gf for instance) or if I reboot my phone it seems to disapear too.

Btw I changed the color of the icon it may help.

**Comment by jahd2602** [comment] 2015-12-07 05:10
Same problem. Changed color of icon. Samsung Galaxy Ace style, Google launcher. Happens always after reboot.

**Comment by licaon-kter** [comment] 2015-12-07 08:07
Did you move the app to the SD Card?

**Comment by jahd2602** [comment] 2015-12-10 01:07
No, can't move either (don't know why)

**Comment by moezbhatti** [comment] 2017-10-04 03:36
Should be fixed in QKSMS 3.0

**Closed by moezbhatti** 2017-10-04 03:36 UTC
Labels: bug: needs repro
