### ISSUE TITLE
Text of Group text (MMS) are not shown

### ISSUE THREAD

**Issue by prg318** [moezbhatti/qksms#1283] opened 2018-08-16 22:25 UTC
### DESCRIPTION
When a group text (MMS sent to multiple recipients) is received by QKSMS, the message is not shown.
![screenshot_20180816-182058](https://user-images.githubusercontent.com/549291/44238106-424d1080-a181-11e8-8521-d27ae15ec365.png)

WORKAROUND:  Go into settings and resync QKSMS messages with the Android message store.  Then, you can view the messages in the stock SMS viewer.

I have experienced this with QKSms free from google play store, QKSMS plus from google play store, and QKSMS from F-DRoid.  I've tested with different sim cards (AT&T and T-mobile) and can reproduce this on Android 8.1 on both LG Nexus 5x and Nokia 6.1 (2018)

### STEPS
1. Receive a MMS text message sent to multiple phone numbers.
2. Try to view in QKSMS

### EXPECTED
Excepted to be able to view MMS text messages in QKSMS

### OBSERVATIONS
Message text is not visible without exporting to android and viewing in another app

I'd be happy to provide any additional details about this - I absolutely love QKSMS but this one thing drives me insane because I get involved in so many MMS group chats

**Comment by moezbhatti** [comment] 2018-08-17 06:29
Thanks for the report! Going to close this one as this is a duplicate of an existing issue, #1125

**Closed by moezbhatti** 2018-08-17 06:29 UTC
