### ISSUE TITLE
Configurable timestamps

### ISSUE THREAD

**Issue by StripedMonkey** [moezbhatti/qksms#1059] opened 2018-04-18 02:37 UTC
Currently the timestamps are just the time in hours and week old messages look as if they were sent this morning because the timestamp doesn't change.

**Comment by realmain** [comment] 2018-04-18 23:30
In my app it shows

Today (April 18th): **16:15**
Yesterday: **Tues 16:15**
2 days ago: **Mon 16:15**
3 days ago: **Sun 16:15**
4 days ago: **Apr 14, 16:15**
5 days ago: **Apr 13, 16:15**

Were you expecting something else? I might be comprehending your post wrong.

**Comment by StripedMonkey** [comment] 2018-04-19 16:42
Yea, that only shows at the beginning of a text chain and (not sure what the limit is) does not show if the conversation lasts for extended periods of time. I was having a rather long conversation with a team member and then didn't speak to them for the rest of the week. Because it was 200+ messages long I can't easily tell what day it was sent on (I.E monday or tuesday) without scrolling through all those messages. I'm requesting that there be a way to find out the day/time that a message is sent individually instead of being at the beginning of a chain.

**Comment by realmain** [comment] 2018-04-19 17:05
I see what the issue is. You can click on a message, and it will tell you the time it was sent/received but not the date/day. I am making a new issue for this with a better title and description. See Issue #1068

Guess we can close out this one.

**Comment by moezbhatti** [comment] 2018-04-19 18:14
Thanks for clarifying! This is a good suggestion, I'll make sure it gets implemented.

I'll close this issue as it will now be redundant with the new one you've made.

**Closed by moezbhatti** 2018-04-19 18:14 UTC
Labels: Discussion
