### ISSUE TITLE
No notification sound when app is open to conversation

### ISSUE THREAD

**Issue by joshhansen** [moezbhatti/qksms#1660] opened 2020-11-23 11:44 UTC
### DESCRIPTION
If I have a conversation open and a message is received in that conversation, no sound is played. The screen timeout on my phone is long, so this means there can be up to about 10 minutes if my phone is sitting open to a qksms conversation where messages received will not play a sound and I will be unaware that a message is sent at all unless I happen to look at that conversation again.

### STEPS
1. Open to a conversation
2. Send a message to that phone in that conversation
3. Don't hear anything

### EXPECTED
A notiication sound still plays on message receipt regardless of if the conversation is already open

### OBSERVATIONS
No sound plays

**Comment by moezbhatti** [comment] 2020-12-13 06:41
Duplicate of 1595

**Closed** 2020-12-13 06:42 UTC
