### ISSUE TITLE
QKSMS became awfully slow after latest update

### ISSUE THREAD

**Issue by RedDragonx** [moezbhatti/qksms#527] opened 2016-06-16 08:04 UTC
Everything was smooth & fast until the latest update (2.6.2)
Usually QKSMS window open instantly after I touch QKSMS icon, but now it took few seconds to loads, and that's just open QKSMS, all other QKSMS task like open a conversation, open settings... is slower as well and make QKSMS unusable.

I restart device, re-install QKSMS but no luck, I'm testing other message app like Textra, ChompSMS... and they all smooth & fast but I still like QKSMS most. Please tell me you can fix this problem.

**Comment by cirelli94** [comment] 2016-06-17 07:15
I do not have any of this problems.
Nexus 5X with 2.6.2 QKSMS

**Comment by romelemperado** [comment] 2016-06-18 03:58
I don't have any problems too with Samsung s3 and Nexus 6P

**Comment by cirelli94** [comment] 2016-06-18 06:19
Maybe try to clean data and cache of QKSMS.

**Comment by RedDragonx** [comment] 2016-06-18 08:40
I tried way possible but no luck so far

**Comment by romelemperado** [comment] 2016-06-21 12:39
I saw the same reviews in Playstore about sluggish performance on 2.6.2 but cannot reproduce.

**Comment by xCOYS** [comment] 2016-06-25 18:40
Made an account just to post here. QKSMS started going really slowly on my HTC One M8. I'm not exactly sure when, but reading this thread and seeing is say "since the last update" seems to fit with my mental timeline. It takes long to open a text from a popup, takes long to open by just pressing the icon, takes long to load my keyboard inside the app, etc. Clearing the app from my phone by pressing the bottom right button and swiping it out of the active apps catalog seems to fix it for awhile, but then it slows down again soon after.

**Comment by woj-tek** [comment] 2016-06-26 12:58
Same issue - clearing the app from app drawer seems to fix the issue for a moment...

**Comment by stevenroose** [comment] 2016-06-27 06:41
I have the same issue, but I thought https://github.com/moezbhatti/qksms/issues/119 was the culprit.

**Comment by Weepangel** [comment] 2016-06-27 09:39
Same issue on my Moto X Play since 2.6.2. It's fast at the beginning but QKSMS becomes slower few minutes later. Maybe memory leak ?

**Comment by cirelli94** [comment] 2016-06-27 12:06
@moezbhatti this seems to be relevant.

**Comment by moezbhatti** [comment] 2016-07-04 04:13
I've been seeing some sluggishness as well, when the app has been left open for a while. Will look into it

**Comment by betsythefc** [comment] 2016-07-08 19:48
Same here, Note 4 on Sprint, not rooted, and it now crashes regularly and is very laggy.

**Comment by Weepangel** [comment] 2016-07-13 18:20
Same in 2.7.0.

**Comment by deplacer** [comment] 2016-07-22 05:56
Same here.. Tested on Samsung J1 Phone

**Comment by betsythefc** [comment] 2016-08-06 18:30
Still encountering this problem.

**Comment by janse** [comment] 2016-09-01 12:00
Nexus 5x, fresh install of Android 6.0.1, fresh install of QKSMS 2.7.1.

After playing with the settings and texting for a day, the app became slow to launch. A few seconds delay to open from app shortcut or recent apps. Once it's open, it's not slow to navigate. 

I disabled the "Only show mobile numbers" setting then cleared the app's cache and it seems to have helped. 

I'm coming from an older phone that had KK, and the messaging app I was using had a little warning saying filtering by mobile numbers could impact performance. So if the slowness is still happening for others, maybe this will help.

**Comment by stevenroose** [comment] 2016-09-01 12:31
Is there anything going on to resolve this? I started to have this more
than a year ago and recently had to move away from QKSMS. I miss it and
want this issue resolved.

NB I believe that a way to automatically delete old messages could be a
starting point. Mine grew slower over time and had thousands of messages in
the end because there is no way to delete them through QKSMS.

**Comment by janse** [comment] 2016-09-01 12:39
For what it's worth, there is a setting to auto-delete messages over x days old. But no setting to delete after a thread has reached x number of messages, which I've seen in other apps.

**Comment by stevenroose** [comment] 2016-09-01 12:58
Ah, that's new then. That's helpful already! Will consider trying QKSMS
again and report back.

**Comment by rjmill** [comment] 2016-09-10 16:37
Chiming in with another data point: I was getting really bad performance when I first started using this, but one of the more recent updates seems to have fixed it on my LG V10.

**Comment by fresheneesz** [comment] 2017-04-03 23:39
I have terrible performance as well. It can take 15 seconds to start up every time I click on the icon or on a message. And even when the application is up and loaded, things often stall...

**Comment by jahd2602** [comment] 2017-04-17 02:36
Moto z play, I migrated from Facebook Messenger SMS function to QK, after a week or so it started to get really slow to open from launcher and from notification. Also, sometimes it opens a different conversation than shown on recent apps, or when opened from launcher, and I have to press back 2, 3 or 4 times to get to the main screen (sometimes the same conversation is multiple times in the back stack). In app navigation and keyboard responsiveness are smooth.

**Comment by geomtech** [comment] 2017-06-17 13:41
android:hardwareAccelerated="true"

More fast if you add this in androidmanifest

**Comment by moezbhatti** [comment] 2017-10-04 05:28
Performance has been drastically improved in QKSMS 3.0, closing now!

**Closed by moezbhatti** 2017-10-04 05:28 UTC
Labels: Bug: Confirmed Repro

**Comment by monkeydri** [comment] 2017-10-31 06:31
Hi @moezbhatti,  3.0 sounds promising ! I love your app but in the meantime I had to switch to Textra, QKSMS 2.7.3 is way just too slow to launch

I could not find any info about QKSMS 3.0, do you have an idea of the features and when it will be ready ?

**Comment by moezbhatti** [comment] 2017-12-28 08:29
An update, the QKSMS 3.0 preview is now available. The releases and source are available here on Github
