### ISSUE TITLE
Customize vibration

### ISSUE THREAD

**Issue by Epse** [moezbhatti/qksms#797] opened 2017-11-14 15:51 UTC
Would it be possible to set the type of vibration for the entire app, or per conversation?

As an example, AwSMS implements this per-conversation, allowing you to choose between multiple sequences of short and long vibrations for notifications.

I can't really find any open source app that does something similar sadly.

I'll also take the opportunity to thank you guys for this rather neat app.

**Comment by moezbhatti** [comment] 2018-01-06 08:17
Duplicate of #388

**Closed by moezbhatti** 2018-01-06 08:17 UTC
Labels: Feature
