### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by akashdeepsingh9988** [moezbhatti/qksms#701] opened 2017-01-22 17:16 UTC
Add backup and restore option in app. Now days mostly all apps provide the backup and restore feature. Add a feature to allow user to backup messages on Google account, G Drive, External Storage or Email.

**Comment by sm4rk0** [comment] 2017-01-23 09:42
Is this a duplicate of #285, or you have a different idea?

**Comment by akashdeepsingh9988** [comment] 2017-01-23 19:10
Yes. mostly apps only have feature to import messages to  External sd card. But i suggest a idea to backup or import the messages to G Drive, Email etc. I think Backup all messages automatically on QKSMS server,G Drive(Like whatsapp), backup all messages via email  is good feature.

**Comment by moezbhatti** [comment] 2017-02-27 06:12
Going to combine the issues, because they're essentially talking about the same thing

**Closed by moezbhatti** 2017-02-27 06:12 UTC
