### ISSUE TITLE
Notification disappears when locked

### ISSUE THREAD

**Issue by Gnat008** [moezbhatti/qksms#735] opened 2017-04-19 16:21 UTC
### DESCRIPTION
When the phone is locked or the screen turns off while QKSMS is open, the app still thinks it's visible and thus immediately removes the new notification. This can very easily cause messages to not be seen for some time if one isn't constantly checking their device.

### STEPS
1. Open QKSMS and lock the phone (does not have to be in a conversation)
2. From another device, send a text message to the locked phone
3. Possibly observe a new message notification briefly pop up, then disappear

### EXPECTED
When the screen is off, new message notifications should not disappear.

### OBSERVATIONS
A new message notification will pop up, then disappear a second later. Upon unlocking the phone, there is no notification, but a quick-reply popup is on the screen and the message shows as unread in the conversation list.

**Comment by sm4rk0** [comment] 2017-09-11 07:35
duplicate of #224

**Closed** 2017-10-04 03:57 UTC
Labels: Bug: Needs Repro
