### ISSUE TITLE
Passcode Lock

### ISSUE THREAD

**Issue by peylight** [moezbhatti/qksms#1543] opened 2019-12-19 22:37 UTC
Hello
Please add passcode lock for a conversion.
I mean it is good to able lock a conversion and unlock by a password.
Thanks for your application.

**Comment by betsythefc** [comment] 2019-12-26 07:00
I would like to second this idea. Tie it into androids default auth, and it'll prompt for the device credentials (be that pattern, code, password, fingerprint, etc) on open.

I think the auth should happen on app start though, with a set-able timeout.

**Comment by moezbhatti** [comment] 2020-01-02 01:22
Duplicate of #492

**Closed by moezbhatti** 2020-01-02 01:22 UTC
