### ISSUE TITLE
Some contact names don't appear...

### ISSUE THREAD

**Issue by olive681** [moezbhatti/qksms#495] opened 2016-05-12 14:31 UTC
### DESCRIPTION

Hi,
I've just installed the App, and have the following problem: some contact names do not appear in my sms list, I just see their phone number.
Do you know why?

**Comment by moezbhatti** [comment] 2016-05-23 03:43
If you tap their avatar, does it open their contact in the Contacts app?

**Comment by olive681** [comment] 2016-05-23 06:49
Yes, if I tap their avatar, a little windows appears from the bottom of the screen, with the name of the contact...

**Comment by DFyson** [comment] 2016-06-06 07:38
I can confirm this has been happening to me too for about half of my contacts. I thought it was maybe the way some numbers are formatted such as (123) 456-7890 vs 123-456-7890 but I tried changing them and it didn't fix it. I'm running CyanogenMod on Android 6. A more frustrating and possibly related bug is #515

**Comment by arvinsim** [comment] 2016-06-16 00:04
I can confirm that this is happening to some of my contacts.

I am running a rooted stock rom on the Note 2, Android 4.4.2

**Comment by moezbhatti** [comment] 2016-07-04 04:11
Merging with #328

**Comment by protist** [comment] 2017-01-31 07:39
I have a similar problem, but the different components do appear to talk to each other on some level.

1. Receive an SMS from a number that is *not* in your contacts (with format `+61 xxx xxx xxx`).
2. Touch the contact icon in the conversation list to add contact.
3. In QKSMS, observe the contact's number with no name.
4. Touch the contact icon again, and be asked to add contact again (as opposed to bringing up the entry for "known" contacts).

*However*, I can browse contacts, including this one, and see the correct number in the same format as above. I can also see a list of messages associated with this contact in the contact app.

Also running CyanogenMod 13.

**Comment by protist** [comment] 2017-05-09 08:38
Is there some way I can manually refresh the database? This is still a problem.

I've also tested the system Messaging program and chompSMS, and both of them also show the number instead of the name.

However, I tried "Handcent Next SMS", and names are shown perfectly. In addition, touching the contact's picture brings up the contact as expected.

**Comment by richardtkemp** [comment] 2017-05-10 20:27
Seeing the same on a Xiaomi Mi 5 running latest update (MIUI 8.1.2.0, Android 6.0.1). Full contact details are visible by tapping on the icon. I don't know if it's a pattern but it doesn't seem to occur on contacts with photos, though it also doesn't occur on all contacts without photos.

**Comment by DFyson** [comment] 2017-06-08 16:23
For me it seems to only be for older contacts and there seems to be a correlation with my older contacts being stored on the SIM card too. I used [Dumbphone Assistant ](https://fossdroid.com/a/dumbphone-assistant.html) to remove them but still no luck.

**Comment by protist** [comment] 2017-06-09 01:06
FWIW I only see it on one contact, which is one of the newest. I don't store any contacts on the SIM card. I've also tried removing and adding area codes, but it doesn't seem to make any difference.

**Comment by moezbhatti** [comment] 2018-01-13 07:43
This should be fixed in QKSMS 3.0

The cache is updated more frequently, and it can be manually refreshed simply by opening the Compose screen

**Closed by moezbhatti** 2018-01-13 07:43 UTC
Labels: Bug

**Comment by fredcooke** [comment] 2018-01-13 09:27
Hey man, looks like the fdroid 3.0 builds are failing: https://f-droid.org/wiki/page/com.moez.QKSMS Could you take a look, I'm interested to try out QKSMS 3.0 as it sounds like it may be a lot better than before ;-)

**Comment by moezbhatti** [comment] 2018-01-13 18:34
Hmm, I can't seem to view the build logs and see what's wrong. I'll take a closer look later today and see if I can sort it out

#841
