### ISSUE TITLE
Feature Request: Treat messages with different number representation as the same contact/thread

### ISSUE THREAD

**Issue by Saijin-Naib** [moezbhatti/qksms#1613] opened 2020-05-21 14:05 UTC
### DESCRIPTION
Messages (1:1) with a contact that has multiple representations of their number are split out into separate threads.

### STEPS
- Contact with number/representation of: +1 (555) 555-5555
- Import message backup/have messages with this contact
- Receive messages from contact with number +15555555555
- Note that messages from/to the simplified representation are grouped separately from the pretty/complex representation, though they are the same _**number**_

### EXPECTED
Messages/Threads (1:1) that share the same number, but different number representation, are treated as the exact same number (as they should be).

### OBSERVATIONS
Messages sent with different representations of the same number are split out into different threads.

### Other
Could be enhanced with/by Issues:  
#1210 
#313

**Comment by moezbhatti** [comment] 2021-01-02 04:17
Sounds like there's a bug here - though it's hard for me to reproduce it without the exact phone numbers that you're testing with. I tried by using the sample numbers you've provided here, but QKSMS is able to correctly identify `+1 (555) 555-5555` and `+15555555555` as the same number, so it might be something specific to the actual number in your case

Could you send me an email with the actual number used, and I can see if I can reproduce the problem?

I recognize that it's been a long time since this issue was opened and you may not be using the app anymore, so I'll close this off until I hear back

**Closed by moezbhatti** 2021-01-02 04:17 UTC

**Comment by Saijin-Naib** [comment] 2021-01-02 04:28
Thanks for replying. As you've guessed, I've unfortunately moved my wife and I off of QKSMS and the Simple Mobile apps as there were too many UX papercuts in them that I could no longer triage for her -_-

I've since re-formatted my phone since QKSMS was no longer receiving any messages (only stock Android Messaging was), so I don't know if I can even reproduce this anymore. I'll re-acquire QKSMS and see if it does the same thing again.

**Comment by moezbhatti** [comment] 2021-01-02 04:30
I'm not sure if this is when you had issues with QK not receiving messages but there was an issue a few weeks ago where all 3rd party SMS apps broke. It was fixed in the latest version of Google's `Carrier Services`: https://play.google.com/store/apps/details?id=com.google.android.ims&hl=en_CA&gl=US

**Comment by Saijin-Naib** [comment] 2021-01-02 04:37
> there was an issue a few weeks ago

Yup! What an absolute... Ugh. Thank you for educating me. Hours wasted, and a ton of messages lost forever for nothing.

Well, I'll re-acquire QKSMS now and get back to you soon. Thank you! I do miss QKSMS. Does it handle RCS because that has been nice.

**Comment by moezbhatti** [comment] 2021-01-02 06:14
No worries - I'm glad to hear it!

And unfortunately no, not yet at least. I plan to implement this once Google opens up the API to 3rd party developers

**Comment by moezbhatti** [comment] 2021-01-02 06:14
Regarding the phone number issue, looks like there's already a ticket open for that. So let me know here if you have an updates: https://github.com/moezbhatti/qksms/issues/1589
