### ISSUE TITLE
[FEATURE REQUEST] Add Titles to threads

### ISSUE THREAD

**Issue by pikurasa** [moezbhatti/qksms#366] opened 2016-01-20 16:43 UTC
Is it possible to be able to add a title to a particular thread?
- Long click the thread
- Select that you want to "add a descriptive title"
- Give it a title

The title should then display instead of the numbers.

This is helpful for those who are subscribed to services like GroupMe, where the phone number displayed is meaningless and it does not make sense to make a contact for the phone number that the texts are sent from.

I can provide an image if you like, but I would need to blur the phone numbers for privacy reasons.

**Comment by moezbhatti** [comment] 2016-01-24 05:48
Completely agree, this is super useful. Especially for group conversations

**Comment by moezbhatti** [comment] 2018-01-09 03:24
Duplicate of #45

**Closed by moezbhatti** 2018-01-09 03:24 UTC
Labels: Enhancement
