### ISSUE TITLE
Atleast give some stability updates.

### ISSUE THREAD

**Issue by Gigas212** [moezbhatti/qksms#1876] opened 2022-06-15 17:24 UTC
### DESCRIPTION
A short description of the issue. 
Example: Conversations aren't marked as read when they are opened from a notification.

### STEPS
1. Steps
2. to 
3. reproduce
4. the 
5. issue.

### EXPECTED
Describe the expected behaviour.

### OBSERVATIONS
Describe what happens instead of the expected behaviour.

**Comment by DarthPleurotus** [comment] 2022-06-22 19:45
The developer seems to have moved on. I am frustrated too.

**Comment by lowendgamer** [comment] 2022-07-04 07:02
> The developer seems to have moved on. I am frustrated too.

Qksms is abandoned now? This makes me sad.

**Comment by moezbhatti** [comment] 2023-01-16 03:08
Just chiming in to say that I'm working on the app again, and I left a comment with some more of my thoughts on #1881 

I'm going to close this ticket since its title is no longer true. That said, there's a real issue you mentioned in your description. If you're still experiencing that, please open a new ticket for it – or rename this one and reopen it with some more info on how to reproduce the error. I've tried testing it myself, and it seems to work perfectly fine for me

**Closed as completed by moezbhatti** 2023-01-16 03:08 UTC

**Comment by Gigas212** [comment] 2023-02-22 07:21
Thank you for the experiment and generous reply.Appreciate it.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
