### ISSUE TITLE
Feature Request: Attach Voice/Sound File

### ISSUE THREAD

**Issue by Saijin-Naib** [moezbhatti/qksms#1615] opened 2020-05-22 01:13 UTC
### DESCRIPTION
Alongside the ability to attach images, it'd be great if we were able to pick and/or record sounds OTF (like image from Camera UX now).

I make use of this fairly often, especially when sending content to family for events/birthdays/anniversaries, etc.

**Comment by FalcionX** [comment] 2020-06-23 02:47
In general record voice in app will be great!!

**Comment by moezbhatti** [comment] 2021-01-02 05:34
Duplicate of #114

**Closed by moezbhatti** 2021-01-02 05:34 UTC
