### ISSUE TITLE
MMS epic fail

### ISSUE THREAD

**Issue by Raptor8888** [moezbhatti/qksms#1572] opened 2020-02-10 11:09 UTC
QKSMS+ contains no support for MMS! You can send photos using MMS (but photos sent via MMS are shrunk to the size of a postage stamp – irrespective of the compression size set); and the app is restricted to strictly allowing photos. This is absolutely ridiculous. Both issues need to be fixed ASAP!

**Comment by moezbhatti** [comment] 2020-02-11 04:17
Duplicate of #1551. If you have any meaningful information to share, please add it to that discussion.

**Closed by moezbhatti** 2020-02-11 04:17 UTC

**Comment by Raptor8888** [comment] 2020-02-11 04:34
Why don't you share some meaningful information – you fucking asshole. 


11 Feb 2020, 12:17 pm by notifications@github.com:
