### ISSUE TITLE
Ability to select part of a message

### ISSUE THREAD

**Issue by ortolot** [moezbhatti/qksms#1586] opened 2020-02-28 09:42 UTC
### DESCRIPTION

This is a feature request.
It would be useful to be able to select part of a message in order to copy it, or share it otherwise. Like you can do in a Web browser for instance.

Example uses:
1. I am ordering something from a merchant website, and in order to pay, I have to provide a code received by SMS. I would like to be able to copy the code from that message instead of remembering it and typing it again, which is error-prone.
2. A friend provided me his address, in a message that says “I live at 4212 Cool street, Niceville 51200, see you tonight”. To go there, I would like to be able to copy the address, without the surrounding text, to paste it into a pathfinder application.

### STEPS

Long tap a word in a message. This selects the entire message.

### EXPECTED

Long tap on a word inside a message would select that word, then the user could use selection handles to adjust the selection boundaries, and copy or share the selected text.

### OBSERVATIONS

Long tap a word in a message selects the entire message. People currently work around this by then creating a new message, pasting the entire original message there, then copying whatever they need from the message writing input box. Then they have to delete all the text in order not to send that new message.

**Comment by moezbhatti** [comment] 2020-03-01 04:36
Thanks for the detailed suggestion! Going to close this one however as it's a duplicate of #1105

**Closed by moezbhatti** 2020-03-01 04:36 UTC
