### ISSUE TITLE
Crash when sending MMS to self

### ISSUE THREAD

**Issue by glacambre** [moezbhatti/qksms#393] opened 2016-02-13 10:21 UTC
Using QKSMS 2.5.2 on Android 5.1.1.
Here's how the bug happened:
1) Created a new contact named "127.0.0.1" the phone number of which is mine.
2) Took a picture (res: 3840*2160, file size: 2,67MO) with my stock phone app.
3) Used the "share" button, selected QKSMS which brought up the Quick Reply interface with the picture embedded.
4) Sent the picture to the "127.0.0.1" contact with the word "test" attached.
Now, whenever I try to open my conversation with "127.0.0.1", the app crashes everytime.

**Comment by Trustmega** [comment] 2016-07-12 12:48
Tried this on 2.6.3 @ android 5.0 and can't reproduce this one.

**Comment by moezbhatti** [comment] 2018-01-13 06:47
This is fixed in QKSMS 3.0

**Closed by moezbhatti** 2018-01-13 06:47 UTC
Labels: Bug: Needs Repro
