### ISSUE TITLE
GIFs are not being properly sent in MMS. 

### ISSUE THREAD

**Issue by aerobahn** [moezbhatti/qksms#274] opened 2015-11-10 20:59 UTC
When i try to send an animated gif it will only send the first still frame of the gif, not the whole thing; The file size of the image is also reduced. 
However, when i tested the same gif on another sms app (Textra), it sent perfectly and was animated on the receiving side (as well as on senders side). 

Thanks for your time.

**Comment by mourningbell** [comment] 2016-01-26 16:43
I'd like to bump this; GIFs aren't sent or received correctly. This isn't so much an enhancement as it is an issue/bug.

**Comment by moezbhatti** [comment] 2018-01-13 07:30
This has been fixed in QKSMS 3.0

**Comment by nvllsvm** [comment] 2018-02-24 19:04
@moezbhatti - I'm experiencing this exact issue in 3.0 beta 2.

**Comment by moezbhatti** [comment] 2018-02-24 21:18
@nvllsvm confirmed, looks like it broke when I switched to a different method of sending images. Will fix this

**Closed** 2018-04-21 22:56 UTC
Labels: Bug, Feature

**Comment by BobSt27** [comment] 2024-06-10 11:32
This is not fixed or has reemerged. Animated gifts are being sent as first frame still image. Quite aggravating. Is there setting to fix it, or is it still a "bug"?
