### ISSUE TITLE
Feature Request: Send messages from browser/desktop

### ISSUE THREAD

**Issue by CrazyHoodlem** [moezbhatti/qksms#1658] opened 2020-11-17 17:32 UTC
It would be nice to send messages from the browser/desktop. Much like the feature that Google Messages has. Theoretically, there just needs to be some kind of WS connection between the phone and desktop on the network. I'll have a look at the app's code later and see what can be done.

**Comment by sm4rk0** [comment] 2020-12-12 03:43
Duplicate of #818

**Closed** 2020-12-13 04:09 UTC
