### ISSUE TITLE
Send button can't be tapped after creating a new message

### ISSUE THREAD

**Issue by krux3r** [moezbhatti/qksms#1135] opened 2018-05-10 15:56 UTC
### DESCRIPTION
When I try to create a new message, I choose the contact, type the message and then I can't press the send button, it does nothing when tapped.

### STEPS
1. Tap the + fab
2. Choose a contact
3. Type anything
4. Press send button, it does nothing in my case.

### EXPECTED
Send button should just send the message.

### OBSERVATIONS
My phone is Huawei P10 Lite, stock 7.0, not rooted.

**Comment by moezbhatti** [comment] 2018-05-10 18:53
Duplicate of #1079

**Closed by moezbhatti** 2018-05-10 18:53 UTC
