### ISSUE TITLE
Showing avatars in conversation list: make it optional

### ISSUE THREAD

**Issue by telebiker** [moezbhatti/qksms#1563] opened 2020-01-24 19:56 UTC
### DESCRIPTION
Showing avatars in conversation list setting is missing (it existed is some previous version)

### STEPS
1. Open settings
2. There's no option to disable/enable userpics in the list of conversations

### EXPECTED
Feature to disable/enable avatars in the list of conversations exists in the settings

### OBSERVATIONS
This feature existed in QKSMS long time ago and was very useful. For example, users who are not assigning avatars to their contacts, don't need this feature. Instead, free space can be used to extend conversation preview. Moreover, this feature was unique to the SMS clients for Android. I'm not sure whether another SMS client existed at all with ability to hide avatars.

**Comment by moezbhatti** [comment] 2020-01-24 19:58
Duplicate of #1030

**Closed by moezbhatti** 2020-01-24 19:58 UTC
