### ISSUE TITLE
MMS unavailable after turning on mobile data

### ISSUE THREAD

**Issue by barongi** [moezbhatti/qksms#1560] opened 2020-01-18 19:44 UTC
### DESCRIPTION
No MMS download option when turning mobile data on.

### STEPS
1. Turn off mobile data.
2. Receive incoming MMS notification.
3. Turn on mobile data.
4. Click on QKSMS icon.
5. Click on contact/sender name in messages list.

### EXPECTED
Expected to see a small download MMS button, like in Google Messages with the same scenario.

### OBSERVATIONS
Clicking on the contact/sender just shows an empty space with nothing to click/download. The MMS is never received.

Nokia 7 Plus
Android 10
QKSMS 3.8.0

**Comment by afish** [comment] 2020-03-15 23:30
I have the same issue. What's more, message is broken completely and it cannot be downloaded by other application like Google Messages https://play.google.com/store/apps/details?id=com.google.android.apps.messaging&hl=en_US

**Comment by moezbhatti** [comment] 2020-03-16 14:14
Duplicate of #118

**Closed** 2021-01-02 03:05 UTC
