### ISSUE TITLE
Feature req : Delay / program one particular SMS

### ISSUE THREAD

**Issue by pwaecker** [moezbhatti/qksms#760] opened 2017-07-31 08:38 UTC
Hi,

After trying different SMS apps, I fixed on QKSMS. QKSMS allows for delaying the sending of every SMS throug the parameters. It would be great to have control on the sending time of a given SMS.
That possibilty would appear when writing SMS, through an option when pushing the "+" button on the right. The clock that appear would allow to parameter in the same screen for the message being written, the sending time.
This new feature allows to program for SMS sending.

Thx for reading !
Pierre

**Comment by moezbhatti** [comment] 2017-10-04 04:44
Duplicate of #137

**Closed by moezbhatti** 2017-10-04 04:44 UTC
