### ISSUE TITLE
No notifications for Group Messages

### ISSUE THREAD

**Issue by rayngo** [moezbhatti/qksms#521] opened 2016-06-13 17:28 UTC
The text info is there, but there is no notification letting me know something new has come in.  Everything is fine and normal with regular texts.  This just seems to be a group text issue.

**Comment by tgp1994** [comment] 2016-07-02 02:54
Pretty sure this is a duplicate of my own, issue #510. I would like to see some dev attention on this - it's pretty bad when you're missing messages like this.

**Comment by moezbhatti** [comment] 2016-07-04 03:27
Yeah, I'll merge them

**Closed** 2016-07-04 03:27 UTC
Labels: duplicate
