### ISSUE TITLE
Enhancement: Do not crop picture received by MMS, just display with a proper aspect ratio

### ISSUE THREAD

**Issue by LrntL** [moezbhatti/qksms#1398] opened 2019-03-25 14:12 UTC
I'm just posting an other idea of enhancement.
Feel free to comment if you think it is interesting.

Enhancement: Do not crop picture received by MMS, just display with a proper aspect ratio (Like Google message app).

Laurent

**Comment by moezbhatti** [comment] 2019-04-02 01:10
Duplicate of #1213

**Closed by moezbhatti** 2019-04-02 01:10 UTC
