### ISSUE TITLE
Viewing all conversations removes notification

### ISSUE THREAD

**Issue by chucktheonewhobutles** [moezbhatti/qksms#303] opened 2015-12-09 19:16 UTC
This isn't technically a big, but it would he helpful if notifications were only removed once the specific conversation itself was opened. This is particularly helpful for people who leave notifications as reminders.

**Comment by jnns** [comment] 2016-02-24 11:19
This is important as it may lead to messages coming in unnoticed. Below are steps to reproduce this bug:

### DESCRIPTION

When a conversation is open a new incoming sms from another contact then don't generate notifications in the notification bar.

### STEPS

1. Open a conversation with person A
2. Your phone is idle, not locked, display is on.
3. You receive an SMS from person B (a vibration or sound may occur if this is set).

### EXPECTED

A notification about person B's text message is displayed in the notification bar.

### OBSERVATIONS

There's no notification in the notification bar. If you set your phone to vibrate or to emit a sound, that's the only thing that can catch your attention to a new incoming message. 

In case you didn't feel or hear the vibration/sound, the new message goes unnoticed. This is problematic because the only hint that there's a new message waiting for you, is the small *unread-dot* next to the particular conversation in the conversation overview. 

I, for one, rarely open the conversation overview intentionally because I tend to just tap on notifications and exit the app to the homescreen button.

**Comment by moezbhatti** [comment] 2016-02-28 21:36
Thanks for the detailed repro steps @jnns

**Comment by moezbhatti** [comment] 2017-12-28 08:34
This is addressed in QKSMS 3.0

**Closed by moezbhatti** 2017-12-28 08:34 UTC
Labels: Enhancement
