### ISSUE TITLE
Nb of unread messages doesn't disapear

### ISSUE THREAD

**Issue by Lolowild** [moezbhatti/qksms#476] opened 2016-04-20 18:43 UTC
Despite the fact that I read all the messages, the little bubble on the app icone doesn't disapear. And the number seems to change when I open certain conversation. 

I think it's happening when I mark a message as read from the popup Window (the check button on the Quick view). 

Hope my explanation will help.

**Comment by moezbhatti** [comment] 2016-05-19 01:23
For repro: This happens generally when an unread message is deleted

**Comment by moezbhatti** [comment] 2018-01-06 08:12
Duplicate of #311

**Closed by moezbhatti** 2018-01-06 08:12 UTC
Labels: Bug: Confirmed Repro
