### ISSUE TITLE
add contact from conversation

### ISSUE THREAD

**Issue by MickaelB** [moezbhatti/qksms#1501] opened 2019-09-24 17:12 UTC
### DESCRIPTION
when i have to add a new contact from sms, i received always invalid number

### STEPS
1. a unknow number send me a sms
2. i click on icon to create a new contact
3. save impossible invalid number

### EXPECTED
open contact to add number and create contact

### OBSERVATIONS
international french  number with + and space

thanks for this great appli

**Comment by moezbhatti** [comment] 2019-09-30 05:17
Duplicate of #1448

**Closed by moezbhatti** 2019-09-30 05:17 UTC
