### ISSUE TITLE
No scroll bar in conversations on Galaxy S8

### ISSUE THREAD

**Issue by bigftguy** [moezbhatti/qksms#784] opened 2017-09-20 06:56 UTC
### DESCRIPTION
No scrollbar is visible in Galaxy S8 when viewing conversations and conversation lists. Only in app settings scrollbar is shown.

### EXPECTED
Scrollbar should be visible so you can understand how many messages you have.

**Comment by sm4rk0** [comment] 2017-09-20 11:37
Duplicate of #384 and partially of #271.
I hope it's included in upcoming update.

**Comment by moezbhatti** [comment] 2017-10-04 05:31
The current version of QKSMS doesn't have scrollbars, but they're being added in the next release (along with fast-scroll support)

**Closed by moezbhatti** 2017-10-04 05:31 UTC
