### ISSUE TITLE
[Feature Request] Mark All Items as Read

### ISSUE THREAD

**Issue by Saroufim** [moezbhatti/qksms#1476] opened 2019-08-23 08:01 UTC
Some of us receive a lot of spam SMS. Just leaving the phone aside for a few hours would let several SMS accumulate as unread. It would be nice if we can mark them all as read in one go via a simple button.

**Comment by moezbhatti** [comment] 2019-08-28 00:27
Duplicate of #1310

**Closed by moezbhatti** 2019-08-28 00:27 UTC
