### ISSUE TITLE
incorrect display of who received the message

### ISSUE THREAD

**Issue by OmlineEditor** [moezbhatti/qksms#1556] opened 2020-01-13 13:39 UTC
### DESCRIPTION
I have two SIM cards in my phone. when a message arrives, the program does not correctly show where the message came from. it confuses SIM card 1 and SIM card 2.

in the example in the picture, the incoming message should come to sim1. your program is not showing correctly. another program is true.

![sms1](https://user-images.githubusercontent.com/13348933/72259991-d7786100-3622-11ea-8b1a-94562112f51c.jpg)

![sim2](https://user-images.githubusercontent.com/13348933/72259990-d7786100-3622-11ea-9af5-0e18385e571e.jpg)

**Comment by OmlineEditor** [comment] 2020-01-14 14:23
additional remark.
the problem is only in incoming messages. outgoing messages are sent from a real and true sim card.

**Comment by Coethium** [comment] 2020-01-23 10:51
Duplicate of #1524

**Comment by Coethium** [comment] 2020-01-23 10:54
I can confirm the bug : 

![Screenshot_20200123_114342_com android mms](https://user-images.githubusercontent.com/20361482/72978450-ca076780-3dd6-11ea-92a9-c38a1d4bfcaf.jpg)

QKSMS 3.8.0
OS : Android 9 (EMUI 9.1.0)
Hardware : Honor 9 (STF-L09)

**Closed** 2020-03-01 04:32 UTC
