### ISSUE TITLE
New Message Suggestion

### ISSUE THREAD

**Issue by Ksmith30** [moezbhatti/qksms#1158] opened 2018-05-23 02:35 UTC
### DESCRIPTION
When composing a new message, the conversation has to be found by backspacing the input.

### STEPS
1. Hit the "+" Floating Action Button.
2. Type a few letters of the name of the contact.
3. When you select the contact, the name appears at the top.
4. However, the letters you typed while searching are still there.
5. In order to access the message field, you have to backspace.

### EXPECTED
When a name is selected, the message history should immediately appear without backspacing.

### OBSERVATIONS
Instead of the conversation appearing, you have to backspace the name if you partially typed it to view the conversation history.

**Comment by moezbhatti** [comment] 2018-05-29 03:49
Duplicate of #1155. Fixed in version 3.2.1 :)

**Closed by moezbhatti** 2018-05-29 03:49 UTC
