### ISSUE TITLE
Can't start new conversation if there's no existing contact

### ISSUE THREAD

**Issue by jtsurf18** [moezbhatti/qksms#856] opened 2018-01-17 00:07 UTC
After clicking new conversation button, the text reads, toe name or number. If I type a number, I cannot start a conversation. I must select a contact.

**Comment by moezbhatti** [comment] 2018-01-17 00:12
Duplicate of #803 

I've implemented a fix for this today, I'll be releasing it in the next update!

**Closed by moezbhatti** 2018-01-17 00:12 UTC
Labels: Bug

**Comment by jtsurf18** [comment] 2018-01-17 00:17
Damn. I searched before I posted. Thanks for the heads up.


On Jan 16, 2018 at 4:12 PM, <Moez Bhatti <notifications@github.com>> wrote:

Duplicate of #803 <https://github.com/moezbhatti/qksms/issues/803>

I've implemented a fix for this today, I'll be releasing it in the next
update!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/moezbhatti/qksms/issues/856#issuecomment-358150921>,
or mute
the thread

**Comment by moezbhatti** [comment] 2018-01-17 00:19
@jtsurf18 no worries, by default the search will only return issues that are open, so it wouldn't have shown up!
