### ISSUE TITLE
No notification when app is open and screen is locked

### ISSUE THREAD

**Issue by benrolfe** [moezbhatti/qksms#560] opened 2016-07-19 14:06 UTC
### DESCRIPTION
This scenario only happens when the screen is locked, and **QK SMS** is open in the background.
When a new SMS arrives, the notification sound is made - however the notification does not appear on the lock screen.
*This only happens if QK SMS is open in the background.*

### EXPECTED
Notification should appear, even if app is open in the background.

**Comment by detly** [comment] 2016-09-29 21:32
On my system, if I'm watching the lock screen when an SMS arrives, the notification appears but then disappears a fraction of a second later.

**Comment by sm4rk0** [comment] 2016-09-30 10:34
Duplicate of #224

**Closed** 2016-10-26 01:04 UTC
Labels: bug: confirmed repro, duplicate
