### ISSUE TITLE
In chat notifications option

### ISSUE THREAD

**Issue by CactiChameleon9** [moezbhatti/qksms#1621] opened 2020-06-17 08:16 UTC
I often find myself waiting for a message from a number in the chat - it would be good if there was an option to have a sound/vibration when a new message is received from the chat that is currently open, so I don't miss a message.

**Comment by moezbhatti** [comment] 2020-12-13 06:41
Duplicate of 1595

**Closed by moezbhatti** 2020-12-13 06:41 UTC
