### ISSUE TITLE
Multiple image MMS not shown

### ISSUE THREAD

**Issue by mechnesium** [moezbhatti/qksms#498] opened 2016-05-15 16:25 UTC
When receiving an MMS with, for example, multiple images attached (rather than individual MMS messages), only the first image in the message is shown.

The MMS should contain thumbnails with all images similar to the stock Messaging app. When selected, one should be able to scroll through all images.

**Comment by davisdude** [comment] 2018-01-15 21:46
This is also true for when you send multiple images at once. On my end, it looks like I only sent one picture, but on the receiver's side (using stock messaging app), all pictures came through.

**Comment by jtsurf18** [comment] 2018-01-17 04:15
Confirmed issue exists for me too

**Comment by moezbhatti** [comment] 2018-03-01 00:09
Fixed in 52b4dae247e6809315996de394b67810ce252a5e

**Closed by moezbhatti** 2018-03-01 00:09 UTC
Labels: Feature
