### ISSUE TITLE
Multilines message TextView does not increase

### ISSUE THREAD

**Issue by babeuloula** [moezbhatti/qksms#1256] opened 2018-07-19 09:13 UTC
Hello,

### DESCRIPTION
When you write a message, the TextView does not increase when you message are going to the next line.

### STEPS
See this video : https://www.youtube.com/watch?v=GrlA-JFNhv4

**Comment by moezbhatti** [comment] 2018-07-19 16:30
Thanks for attaching a video! Marking this as a duplicate of #1078

**Closed by moezbhatti** 2018-07-19 16:30 UTC
