### ISSUE TITLE
Soft buttons are invisible or barely rendered.

### ISSUE THREAD

**Issue by jeebsorg** [moezbhatti/qksms#1197] opened 2018-06-16 14:32 UTC
The common Android buttons throughout most apps (triangle pointing down or left, circle, and square) are not rendered appropriately in QKSMS+, built by F-Droid. If you press where they should be, they function appropriately. If you look very closely, you can barely see the outlines of the buttons, so they are not totally invisible to the keen observer.

No fancy steps to reproduce this issue. It occurs globally throughout QKSMS+.

Thanks!

**Comment by moezbhatti** [comment] 2018-06-17 18:27
Duplicate of #1176

**Closed by moezbhatti** 2018-06-17 18:27 UTC

**Comment by jeebsorg** [comment] 2018-06-21 01:56
Thank you @moezbhatti 
The dark theme looks great, by the way. I don't know why I didn't think to try that =)
