### ISSUE TITLE
Feature request: backup the blocked numbers and block messages

### ISSUE THREAD

**Issue by Iey4iej3** [moezbhatti/qksms#1810] opened 2021-08-18 16:47 UTC
I propose to support backup of the blocked numbers and block messages. This is especially useful when I want to migrate SMSs to another phone, so that I don't need to reinput all the blocked numbers and retain a list of blocked numbers.

**Comment by xxxxme** [comment] 2023-03-18 14:45
Duplicate of #1745.

**Closed as completed** 2023-03-18 15:44 UTC
