### ISSUE TITLE
MMS – epic fail 

### ISSUE THREAD

**Issue by Raptor8888** [moezbhatti/qksms#1574] opened 2020-02-11 18:05 UTC
QKSMS+ contains no support for MMS! You can send photos using MMS (but photos sent via MMS are shrunk to the size of a postage stamp – irrespective of the compression size set); and the app is restricted to strictly allowing photos. This is absolutely ridiculous. Both issues need to be fixed ASAP!

**Comment by moezbhatti** [comment] 2020-02-11 18:07
Duplicate of #1551. Please be respectful and stop spamming this repo

**Closed by moezbhatti** 2020-02-11 18:07 UTC

**Comment by Raptor8888** [comment] 2020-02-11 18:13
GO FUCK YOURSELF ASSHOLE. 


12 Feb 2020, 2:07 am by notifications@github.com:
