### ISSUE TITLE
SMS Restore Problem

### ISSUE THREAD

**Issue by mimonirbd** [moezbhatti/qksms#1665] opened 2020-12-10 13:17 UTC
I have backup my all SMS via QKSMS app and then Again I restored the backup file. But it can **only show the my sent SMS**, **_can't show any received SMS_**. So, I facing a big problem. How can I fix the problem?
Please help me as soon as possible.

**Comment by moezbhatti** [comment] 2020-12-13 07:32
Duplicate of #1644

**Closed by moezbhatti** 2020-12-13 07:32 UTC
