### ISSUE TITLE
Android webview crashes

### ISSUE THREAD

**Issue by Ithilden** [moezbhatti/qksms#1045] opened 2018-04-16 01:15 UTC
### DESCRIPTION
When I first open the app and go to a conversation my Android System Webview sends a crash popup
### STEPS
1. Open app
2. go to any conversation

### OBSERVATIONS
Only happens on first opening of the app, doesn't crash if I open it then go back to the all conversations menu then go into a different conversation.

**Comment by moezbhatti** [comment] 2018-04-16 01:25
Duplicate of #1024

**Closed by moezbhatti** 2018-04-16 01:25 UTC
