### ISSUE TITLE
Search does not appear to have indexed all conversations

### ISSUE THREAD

**Issue by ajzett** [moezbhatti/qksms#1007] opened 2018-04-09 11:33 UTC
## Problem
If I search the inbox for a word, an incomplete list of instances returns.

## Attempts to fix
Re-sync with android database in settings

## Version Info
QKSMS 3.0.4 (fresh install), LineageOS 14.1

Edit: After playing around with it today, it seems it's just returning a list of names that match, rather than search terms. In this case, is searching texts a planned feature?

**Comment by moezbhatti** [comment] 2018-04-09 21:00
The issue is fixed in 223d789f5f1de219867226cba417f83bbffc7537, also referenced by #999 

And searching for text within conversations will be implemented later on. It looks like I don't have an issue up for that, so I'll open one now. #1010

**Closed by moezbhatti** 2018-04-09 21:00 UTC
