### ISSUE TITLE
encryption

### ISSUE THREAD

**Issue by ADepic** [moezbhatti/qksms#1303] opened 2018-09-13 22:10 UTC
Is it possible to encorporate a encryption protocol, such as the silence encryption protocol? Having a encryption protocol for qksms --> qksms users would be great along with the most beautiful messaging app.

**Comment by buzuck** [comment] 2018-12-30 18:14
Agreed!

But, isn't it a duplicate of #458 ?

**Comment by ADepic** [comment] 2018-12-30 19:52
Yes it is please close issue as duplicate

**Closed** 2019-06-25 15:04 UTC
