### ISSUE TITLE
Website, GIF, etc. preview

### ISSUE THREAD

**Issue by Inukinator** [moezbhatti/qksms#1164] opened 2018-05-28 11:29 UTC
### DESCRIPTION
Previewing a website when linked, and maybe show media, when media.

### EXPECTED
I'd like to see a short preview for any link I'm about to click.

### OBSERVATIONS
A link only has a the clickable link, and no meta information or anything.

**Comment by sm4rk0** [comment] 2018-05-28 11:51
I would like a way to turn this off if this feature request is accepted.
While it may be practical and eye-candy, it's not respecting the user's privacy:
https://www.reddit.com/r/privacy/comments/8dhw21/whatsapp_users_ip_disclosure_with_link_preview/
https://github.com/telegramdesktop/tdesktop/issues/687

**Comment by Inukinator** [comment] 2018-05-28 12:13
There _can_ be a proxy setting for users who want the eye candy (me!) and still want _some_ privacy!

**Comment by moezbhatti** [comment] 2018-08-14 14:52
Just noticed that this is a duplicate of #380

**Closed by moezbhatti** 2018-08-14 14:52 UTC
Labels: Feature
