### ISSUE TITLE
QKSMS dont send any message

### ISSUE THREAD

**Issue by crazymonster999** [moezbhatti/qksms#511] opened 2016-06-05 10:08 UTC
Hello,

On a new phone, the soft dont want to send any sms or mms.
It tels immediately an error message that sending failed.
It could see all received message and history from the built un software.
As asked automatically by Android, I put QKSMS as the main application for managing text messages.

There is no troubles with the built in software, when I roll back to, as main app.

MMSC and co are automatically configured for "Free" french telephony company.

### Configuration
QKSMS version : V2.6.1
Telephone : Oukitel k6000 Pro
Android version : 6.0
Oukitel build version : OUKITEL_K6000_Pro_V2.0_20160503

Many thanks in advance for your help.

**Comment by drozdu** [comment] 2016-06-24 09:12
I can confirm this, but only if 2 sim cards are present. With single one everything works.

QKSMS version: 2.6.2
phone: Leeco x800
android 5.0.2

**Comment by moezbhatti** [comment] 2016-07-04 04:12
The app currently doesn't have dual sim support, and I don't have plans to add it in the near future, as I don't have a device I can test this on. Closing issue for now

**Closed by moezbhatti** 2016-07-04 04:12 UTC

**Comment by crazymonster999** [comment] 2016-07-04 08:17
Hello,
My phone support 2 sim cards, but I use only one, on the first slot.
Best regards

**Comment by woj-tek** [comment] 2016-07-04 20:04
my 3 cents - stating definite "wontfix" as more and more devices (especially the lower-end) come as dual-sim is a bit odd. I quite recently got such device (and while dual-sim funcionality wasn't high on my list it was a nice bonus) and it turned out that such capability is quite handy...

**Comment by moezbhatti** [comment] 2016-07-05 05:16
Sorry, the tag `wontfix` seems a bit blunt. The reason I tagged it with that is because personally, I won't be able to fix it any time in the foreseeable future. And in case any other developers wanted to add dual sim support, there's already an issue for that: #207

I should have been more clear as to why this issue doesn't need to be open, rather than just tagging it and closing it 

cc @woj-tek

**Comment by woj-tek** [comment] 2016-07-05 08:23
OK, cool - thanks for the explanation - it makes perfect sense :-)

**Comment by drdink** [comment] 2018-05-17 08:05
Workes with my Blu Vivo XL2 on Marshmallow & Nougat. Stopped when I upgraded to latest version. No options in settings to change SMS settings like in older versions of QKSMS.
Updated version looks good.
