### ISSUE TITLE
[BUG] Scroll bar is missing in conversation and list

### ISSUE THREAD

**Issue by therob84** [moezbhatti/qksms#384] opened 2016-02-07 14:24 UTC
I can't see any scroll-bar when scrolling through the conversation list or inside a conversation.

As I can't find any reason why this should not be there, I conclude it is a bug?!

I use v2.5.2 as standard app with Android 5.1@Fairphone2.

**Comment by moezbhatti** [comment] 2016-02-28 21:14
I'd like to add fast-scroll functionality to both of these screens

**Comment by sm4rk0** [comment] 2016-08-06 13:59
Duplicate of #271

**Closed** 2016-08-06 23:09 UTC
Labels: duplicate, enhancement
