### ISSUE TITLE
Web previews of links that are sent in chat

### ISSUE THREAD

**Issue by Shadowspear123** [moezbhatti/qksms#1428] opened 2019-05-12 15:05 UTC
### DESCRIPTION
Currently, links sent in the chat don't show an image preview like they do on android messages and other SMS applications. 
I know there was an issue a long time ago about the security of this feature, but a simple way to mitigate the risk would be for the user to tap on the image to load it (tap to load preview)

Also, I was wondering if Qksms will support RCS in the future.

**Comment by moezbhatti** [comment] 2019-05-13 03:33
Duplicate of #380 


And yep, I'm planning to add support for it as soon as access is given to 3rd party apps!

**Closed by moezbhatti** 2019-05-13 03:33 UTC
