### ISSUE TITLE
[Feature Request] Merge conversations

### ISSUE THREAD

**Issue by sling-shot** [moezbhatti/qksms#433] opened 2016-03-10 17:17 UTC
### DESCRIPTION
It would be extremely helpful in certain situations if 2 or more conversations could be merged into a single conversation. Example in case of a person having 2 different mobiles numbers and using whichever depending on which has the best reception at his location. A conversation with him will be split over 2 unless both can be merged.

Also commercial SMS say from a bank arrive from different headers such as VM-SBI, VX-SBI, TV-SBI etc. Merging them into a common SBI or a user selected option could make life much easier.

This feature is present in another application called Disa.

**Comment by M2ck** [comment] 2016-03-27 10:36
Duplicate of #313

**Closed** 2016-07-06 05:51 UTC
Labels: duplicate, feature
