### ISSUE TITLE
Add number and type of number.

### ISSUE THREAD

**Issue by OmlineEditor** [moezbhatti/qksms#1558] opened 2020-01-13 14:08 UTC
Now there is only the name of the sender. Add the phone type and phone number field.
![fi](https://user-images.githubusercontent.com/13348933/72262103-4657b900-3627-11ea-828b-ebb1eda49f24.jpg)

**Comment by moezbhatti** [comment] 2020-01-14 00:04
Duplicate of #439

Thank you for the mockups though! Going to move this up in my todo list

**Closed by moezbhatti** 2020-01-14 00:04 UTC
