### ISSUE TITLE
MMS image preview is same for all images

### ISSUE THREAD

**Issue by Atmanbay** [moezbhatti/qksms#31] opened 2015-03-03 01:38 UTC
The preview shown for all images is the preview of the most recently received image. Clicking on the preview shows the correct image

**Comment by srcreigh** [comment] 2015-03-19 05:04
This is the silliest bug! Neither moez nor I can reproduce it. @Atmanbay we'll need your (or someone else's) help to fix this bug and perform testing since we don't have the ability to repro on our own.

I can make a post on our G+ testing community about fixing this. We can try and get a bunch more people to help out so that it's not just one person.

**Comment by mperez19** [comment] 2015-03-26 01:17
@srcreigh I am also seeing this bug. How can I help you fix it?

**Comment by ebony76** [comment] 2015-05-01 02:08
i have also had this bug from day 1. Even before being in the play store. Verizon S5

**Comment by srcreigh** [comment] 2015-05-01 02:17
We picked up a Galaxy S3 the other day so we can test. Fix out soon!

**Comment by sloonark** [comment] 2015-05-19 09:37
This happens for me too on a Galaxy S4.

**Comment by Mitheren** [comment] 2015-07-13 01:04
This is still happening to me as well (Galaxy S6, v 1.10.0). If you still need help reproducing it I'd love to give you a hand.

**Comment by Samcfuchs** [comment] 2015-08-18 22:59
Could not repro on Moto X 2013.

**Comment by moezbhatti** [comment] 2017-10-04 03:52
Should be fixed in QKSMS 3.0

**Closed by moezbhatti** 2017-10-04 03:52 UTC
Labels: Bug: Needs Repro
