### ISSUE TITLE
partial selection of text in a message

### ISSUE THREAD

**Issue by franco27** [moezbhatti/qksms#1751] opened 2021-02-19 23:08 UTC
Hello

Currently when we select a message in a conversation from a contact, we can only copy the entire text into the clipboard. 
I would like to be able to select and copy text partially in a single message. 

When we receive an SMS from a service, with a code or password for validation. 
it would be convenient to be able to copy this code from a message.

**Comment by franco27** [comment] 2021-02-19 23:43
2 other features I would like:
1) I would like to be able to configure a repetition of sound notifications for received SMS.
example: a number of times with the duration.
every 5 minutes or 10 minutes or 30 minutes repeat the buzzer 3 times, 5 times, 10 times.
2) in the list of contacts' conversations, customize the display and be able to sort them by date.
example, separate with 'today', 'yesterday', 'this week', 'last week' and 'previously'.
Group the most recent messages received in the list of conversations of contacts with these periods.

**Comment by moezbhatti** [comment] 2021-02-20 17:44
Duplicate of #1105

**Comment by moezbhatti** [comment] 2021-02-20 17:45
As for your other suggestions, 2. is likely not something I'll be implementing, but feel free to open an issue for 1. if there isn't one already!

**Closed by moezbhatti** 2021-02-20 17:44 UTC
