### ISSUE TITLE
Attach Pictures from Google Photos

### ISSUE THREAD

**Issue by JPDVM2014** [moezbhatti/qksms#1130] opened 2018-05-08 13:34 UTC
Are there any plans to implement attaching photos from online services such as Google Photos? I keep very few pictures on my device storage, and it would be convenient to not have to download them before attaching to a message. Thanks!

**Comment by moezbhatti** [comment] 2018-05-18 17:28
Duplicate of #972

**Closed by moezbhatti** 2018-05-18 17:28 UTC
Labels: Enhancement
