### ISSUE TITLE
SMS occasionally fails to send

### ISSUE THREAD

**Issue by kocane** [moezbhatti/qksms#270] opened 2015-11-07 00:20 UTC
I'm having this issue where sometimes, seemingly random, text messages wont get sent. They're stuck at "sending". Even if I send another one right after, which gets sent and delivered, the previous on does not go anywhere. All is good when I use the stock messaging app (xperia lollipop 5.1.1) and if I switch back to that, the messages that QKSMS failed to sent off will eventually be sent by the stock app.

What on earth can it be? Kind of seems to me like these third party texting apps functioned better back in the day where they were dependent on the stock app...

**Comment by licaon-kter** [comment] 2015-11-07 06:50
Had this too on Xperia 5.1.1 w/ QKSMS 2.2.1.

**Comment by licaon-kter** [comment] 2015-11-11 09:01
And after few days it happens on 2.2.4 (from Github) too. :(

**Comment by licaon-kter** [comment] 2015-12-20 13:14
Since then it worked ok, today it happened again, retried a dozen times to no avail. Left it alone for 30 minutes, now it's working.

**Comment by Kocane** [comment] 2015-12-20 13:25
Meh, I stopped using it. I want sms to be reliable above all and it doesn't seem like the devs care

**Comment by moezbhatti** [comment] 2015-12-21 06:41
Are you sending the messages from inside the app or from QK Reply? @Kocane

**Comment by licaon-kter** [comment] 2015-12-21 08:52
For me it happened while in the app, opened a new message (with a contact that I never messaged from QKSMS).

**Comment by licaon-kter** [comment] 2015-12-22 09:24
And again yesterday, still on 2.2.4.
I've updated now to 2.4.0, I'll see if it happens again.

**Comment by Zayon** [comment] 2015-12-23 15:38
Hi, it happens to me a lot it's really annoying.

I can confirm it happens with BOTH QK reply and from inside the app. The worst case is with QK Reply as you don't see your text hasn't been sent.

I'm using a nexus 5 with android 6.0 and 2.4.0 QKSMS from F-Droid. 
Also I changed my carrier recently and it changed nothing and it doesn't happen with others SMS apps.

**Comment by licaon-kter** [comment] 2015-12-24 08:24
So again it happened, now, I did press send and I closed the screen (not directly, I closed the book case flap and GravityScreen will turn screen off and lock the phone), so maybe this is the reason!?

After a while, I unlock the phone and lo and behold, messages unsent.

And another thing, I now had 2 messages as `not sent`, this new one and the one from a day ago, maybe related to https://github.com/qklabs/qksms/issues/310
An interesting thing is that the previous message was a first message, and now I can't actually open the/a conversation to see it failed (or to cancel it), so it's stuck there (in QKSMS's cache?!).

**Comment by moezbhatti** [comment] 2015-12-24 23:45
So is the message:

Disappeared?
Stuck sending?
Failed?

**Comment by licaon-kter** [comment] 2015-12-25 00:09
Failed. Toaster says fail.

**Comment by licaon-kter** [comment] 2015-12-29 19:20
And again yesterday. :(

**Comment by fredcooke** [comment] 2015-12-31 10:41
I have had quite a few legitimate failures due to dodgy reception/no data connection. For these the most annoying thing is a lack of awareness of the connectivity status and associated automatic retry behaviour. Not sure how the Samsung or hangouts code works, but one of these only requires an explicit resend sometimes, not immediately/always.

**Comment by licaon-kter** [comment] 2015-12-31 11:30
Signal is ok, after some time ( 30 minutes ) I can send again.

**Comment by licaon-kter** [comment] 2016-01-09 22:00
So today it updated to 2.5.1. 
After some hours it failed to send again, only a heads up appears with `3 failed messages` that does nothing if I click it.  (3 from the past I guess !?)

I rage uninstall it right then and there, switched back to default app, which worked as expected always.

I'll be back after sometime maybe. 

Cheers

**Comment by licaon-kter** [comment] 2016-06-05 07:44
2.6.1, still an issue, after maybe 2 weeks without problems, now it fails to send.

**Comment by Trustmega** [comment] 2016-06-07 14:48
I have the same issue on 2.5.5 running on a 100% stock galaxy s5 (SM-G900F) running android 5.0

The bug happens more often in threads with a lot of messages, like over 1000. It becomes even more noticeable the more messages there are in a thread. Today i had it happen to a thread with only 15 messages though.

Both quick-reply and texting through the app itself is affected. It is also a lot more likely to fail when you quickly lock the phone after pressing send, or change to another app. It never happens when i stay in the app until "sending.." is changed to the time you sent it.

**Comment by licaon-kter** [comment] 2016-06-07 14:57
It happens on smaller message lists mostly, here.
But I do have delayed sending and I'm eyeing that for being at fault.

I've deleted all data, re-setup it with the 3 sec default delay again, next time it fails I'll disable the delay to see how that goes.

**Comment by Trustmega** [comment] 2016-07-12 12:56
I havent had this issue in a while, has it been solved?

**Comment by licaon-kter** [comment] 2016-07-12 16:04
It failed me once, but it looked like my signal was low, so it was not it. Might be closed for now I guess.

**Comment by licaon-kter** [comment] 2016-08-07 18:01
Yet again today, and at least once more in the last month. :(

Plenty of signal, stop app, nothing, cleared some data (not all), nothing. 

Switched to stock app, no issue, sends right away.

Xperia 6.0.1

**Comment by hiciu** [comment] 2016-10-15 20:41
I'm having the same issue. Motorola moto g2, android 6.0, not rooted, qksms 2.7.3 (2.7.2 was the last version I had this issue with). I'm using f-droid.org build. Delayed sending is enabled and set to 3 seconds. Messages are stuck on "sending...", these stuck messages are not visible in the stock app.

I don't have reliable repro.

**Comment by geomtech** [comment] 2017-06-17 13:51
Same on Huawei P8.

I know why, i have the same issue on "Android Messages" of Google but after i add my phone number in settings, it was good. So, if we have the same feature on QKSMS, i think it will be good.

It's because some operators don't put the phone number in SIM, if you have "Unknow" in your settings of your phone, it's the right problem.

**Comment by moezbhatti** [comment] 2017-10-04 03:44
Should be fixed in QKSMS 3.0

**Closed by moezbhatti** 2017-10-04 03:44 UTC
Labels: bug: needs repro
