### ISSUE TITLE
Can't select multiple conversation 

### ISSUE THREAD

**Issue by fazlerabbi37** [moezbhatti/qksms#1032] opened 2018-04-14 03:49 UTC
Hi there, I installed QKSMS through F-Driod and in last update I got QKSMS+. Everything looks and works fine but that a feature that I really miss is selecting multiple conversation which was available in QKSMS. Hope to see this feature back as I am sure it is useful for many of us. Cheers!

**Comment by moezbhatti** [comment] 2018-04-14 06:07
Duplicate of https://github.com/moezbhatti/qksms/issues/874

**Closed by moezbhatti** 2018-04-14 06:07 UTC
