### ISSUE TITLE
Marking one message as read causes all QKSMS notifications to disappear

### ISSUE THREAD

**Issue by woj-tek** [moezbhatti/qksms#631] opened 2016-09-09 11:30 UTC
### DESCRIPTION

When having notifications for more than one thread/message/contact, marking one of them as read from notification causes all notifications to disappear.
### STEPS
1. receive >2 messages from separate contacts;
2. >2 notifications are displayed;
3. select one of them in the notifications and from the expanded actions choose 'mark as read'
### EXPECTED

Single message is marked as read and other notifications persists;
### OBSERVATIONS

All notifications from QKSMS are gone

**Comment by moezbhatti** [comment] 2016-09-22 14:40
I can't reproduce this myself

Does this happen for you while the app is open in the foreground, or no matter which app you're looking at?

**Comment by woj-tek** [comment] 2016-09-23 10:17
OK, I've just tested it again and seems to work fine now. I'll update the ticket if I found a way to reproduce it (or was there an improvements recently?)

**Comment by deplacer** [comment] 2016-09-23 10:45
Same here.. to reproduce mark more than 2 conversation as unread to show notifications.
click the top notification.

**Comment by moezbhatti** [comment] 2016-09-23 21:02
@deplacer are you able to reproduce it? Or does it work fine for you?

**Comment by deplacer** [comment] 2016-09-24 01:58
Yes I can.. try to mark 3 conversation as unread to produce notification without waiting incoming sms then minimize qksms and click the top notification.

**Comment by sm4rk0** [comment] 2017-03-10 13:37
Isn't this related to #356 and thus #303, too?

**Comment by woj-tek** [comment] 2017-03-11 16:35
Reading linked issues... yeah, seems so -- most likely the underlying mechanism is the same: no matter how the "read action" is executed it clear the notification for all conversations, be that marking from notification or opening thread.

**Comment by moezbhatti** [comment] 2018-01-06 08:13
This is fixed in QKSMS 3.0

**Closed by moezbhatti** 2018-01-06 08:13 UTC
Labels: Bug: Needs Repro
