### ISSUE TITLE
Partial text copying

### ISSUE THREAD

**Issue by nikolowry** [moezbhatti/qksms#1554] opened 2020-01-12 17:17 UTC
### DESCRIPTION
Request for partial text copying. Mimicking [Slide's](
https://github.com/ccrama/Slide) comment text copying functionality could be one way to implement such a feature.

[Screen capture of Slide's comment text copying functionality](https://neeks.me/cloud/index.php/s/jT6dzBKg4Z2wGK6)

**Comment by moezbhatti** [comment] 2020-01-12 17:18
Really nice implementation. Marking this as a duplicate of #1105

**Closed by moezbhatti** 2020-01-12 17:18 UTC
