### ISSUE TITLE
Text on your computer

### ISSUE THREAD

**Issue by peylight** [moezbhatti/qksms#1565] opened 2020-01-29 19:44 UTC
Hello
I like to have texting on my computer (I have a linux OS and someone maybe have windows)
I mean like a messenger on my computer texting is very nice.
By an application we can do this (Messages by Google)
https://messages.android.com
Unlike Google, QKSMS is safe.
It wiil be nice if QKSMS have this feature.

**Comment by moezbhatti** [comment] 2020-01-29 23:15
Duplicate of #818

**Closed by moezbhatti** 2020-01-29 23:15 UTC
