### ISSUE TITLE
New contact names not displayed in QKSMS conversation list

### ISSUE THREAD

**Issue by spocko** [moezbhatti/qksms#1208] opened 2018-06-21 23:04 UTC
### DESCRIPTION
Contact number instead of contact name is displayed in QKSMS if a conversation with a new contact is initiated externally.

### STEPS
1. Create a new contact in the default contacts app
2. In the contacts app, choose the option to send a message to the new contact
3. In QKSMS, compose and send a message to this new contact
4. Note that the contact number is shown in the QKSMS conversation list, not the contact name
5. Open an other messaging app such as Android Messages or Samsung messages. Note that the contact name is shown instead of the number.
6. Go back into QKSMS and re-sync messages. Note that QKSMS now shows the contact name instead of the number.

### EXPECTED
QKSMS should always show contact name if available, instead of contact number.

### ENVIRONMENT
QKSMS 3.3.2 on Android 6.0.1. QKSMS is set as default messenger.

**Comment by spocko** [comment] 2018-07-03 21:42
Another variation of this issue:

1. Receive incoming message from unknown contact. QKSMS shows the contact number in the convo list as expected.
2. Add that number into your contacts with a name.
3. QKSMS still shows the contact number instead of name in the convo list.
4. Resync messages
5. Now QKSMS shows the contact name in the convo list.

This is with QKSMS 3.3.6. In both cases, it seems like the root issue is that QKSMS does not automatically sync new contact names.

**Comment by moezbhatti** [comment] 2018-08-14 06:52
Just noticed this is a duplicate of #329 - going to close this one!

**Closed by moezbhatti** 2018-08-14 06:52 UTC
Labels: Bug

**Comment by jugendhacker** [comment] 2019-06-24 19:33
> Just noticed this is a duplicate of #329 - going to close this one!

@moezbhatti it is indeed duplicated but it still appears in 3.6.6!

**Comment by moezbhatti** [comment] 2019-06-24 19:34
Reopened that one, I have indeed still been hearing reports of this issue still happening
