### ISSUE TITLE
No notification sound/vibration when conversation window open

### ISSUE THREAD

**Issue by ultrafs** [moezbhatti/qksms#778] opened 2017-09-09 08:40 UTC
### DESCRIPTION
If the conversation window is left open and a new message comes in there is no notification tone or vibration. This happens if the screen is on or locked/off

### STEPS
1. open a conversation
2. wait for a message
3. no sound if one comes in

### EXPECTED
A notification! :-)

### OBSERVATIONS
This is the same behavior as the android messaging app - which is why downloaded this in the hope that wasn't the case. as this is open source, there's a chance it can be fixed :-)

**Comment by sm4rk0** [comment] 2017-09-11 07:34
Duplicate of #224

**Comment by moezbhatti** [comment] 2018-01-12 02:58
This is fixed in QKSMS 3.0

**Closed by moezbhatti** 2018-01-12 02:58 UTC
