### ISSUE TITLE
[BUG] New SMS - rotation of screen

### ISSUE THREAD

**Issue by Woodzrul** [moezbhatti/qksms#1214] opened 2018-06-24 08:58 UTC
Device: OnePlus 2 A2001
Version: 7.1.2
QKSMS: 3.3.4

### DESCRIPTION
New SMS whilst entering a mobile number - rotation of screen
Example: When creating a new SMS and entering the mobile number manually, before confirming if I rotate my phone (screen rotates) then the mobile number that you've started entering disappears and you have to start over.

### STEPS
1. Launch QKSMS
2. Tap the FAB (New SMS)
3. Type a mobile number (For example, 07777777777)
4. Do not proceed any further
5. Turn phone to rotate screen
6. Number disappears that you've just typed

### EXPECTED
Mobile number should remain despite the screen having rotated.

### OBSERVATIONS
N/A

**Comment by moezbhatti** [comment] 2018-06-25 05:09
Duplicate of #1058

**Closed by moezbhatti** 2018-06-25 05:09 UTC
