### ISSUE TITLE
App crash after composing MMS and then again when navigating back to conversation

### ISSUE THREAD

**Issue by bundik** [moezbhatti/qksms#540] opened 2016-06-30 20:13 UTC
### DESCRIPTION

I'm observing 2 crashes. When I send compose a MMS with picture attached from gallery. The message will be probably created, but then it fails and the application crashes. 
### STEPS
1. Compose a MMS to someone.
2. Only a picture with a single line of text.
3. Send message.
4. Observe app crash.
5. Re-open and have a look on the conversation with that person - crashes again.
### EXPECTED

No crashes.
### OBSERVATIONS

I've managed to capture android logs:
[crash_mms_composing.txt](https://github.com/moezbhatti/qksms/files/342293/crash_mms_composing.txt)
[crash_navigating_to_conversation.txt](https://github.com/moezbhatti/qksms/files/342294/crash_navigating_to_conversation.txt)

I have had to use the native SMS/MMS application to remove messages (there were 2 MMSes) from that conversation.Once they were gone, app worked properly.

**Comment by moezbhatti** [comment] 2016-07-04 04:15
Can't reproduce this on my device

What phone and Android version are you using?

**Comment by bundik** [comment] 2016-07-04 18:32
I'm using Sony Z3 compact. Android 6.0.1. Specifically a custom build ROM [23.5.A.1.238 SLiMM 2.0](http://forum.xda-developers.com/z3-compact/development/rom-slimm-t3359831)
I can reproduce this every time. All other apps are working correctly. I'm willing to load a a test version if you need more details & logs.

**Comment by moezbhatti** [comment] 2016-07-05 06:06
Awesome, thanks for the help. I'll let you know if I have any updates

**Comment by qraq** [comment] 2016-08-17 08:10
I have the same issue on Xperia Z5 Compact (E5823). 
Android 6.0.1, stock ROM, compilation 32.2.A.0.253.

**Comment by moezbhatti** [comment] 2018-01-13 07:42
This should be fixed in QKSMS 3.0

**Closed by moezbhatti** 2018-01-13 07:42 UTC
Labels: Bug
