### ISSUE TITLE
Crash on trying to create new thread

### ISSUE THREAD

**Issue by GeoZac** [moezbhatti/qksms#1559] opened 2020-01-13 15:49 UTC
### DESCRIPTION
The application crashes when trying to create a new thread using Compose activity. The crash only happens for a contact who hasn't been messaged yet.

### AFFECTED VERSION
v3.8.0-beta1

### STEPS
1. Start Compose Activity either using the FAB or using app shortcut
2. Select a contact app with no message history

### EXPECTED
A conversion screen should open up with number assigned

### OBSERVATIONS
App crashes
Crash log: [here](https://haste.aicp-rom.com/atuxukacoc)

**Comment by moezbhatti** [comment] 2020-01-13 23:59
Duplicate of #1555

**Closed by moezbhatti** 2020-01-13 23:59 UTC
