### ISSUE TITLE
No notification for MMS

### ISSUE THREAD

**Issue by Jrdnkasparek** [moezbhatti/qksms#583] opened 2016-08-08 15:22 UTC
### DESCRIPTION
No longer receiving notifications when I get a picture message

### STEPS
1. Send Picture from other phone to my phone
2. Expect to hear notification, No notification is received
3. Open QKSMS, message is there and marked as new

### EXPECTED
Expect to receive notification for new mms

### OBSERVATIONS
No notification is received but new message is seen when opening app
-Note: Normal sms messages come in just fine

** Sorry if I did this wrong, first time poster

**Comment by heyforgetit** [comment] 2016-08-16 15:57
I am not getting any notification sound, getting vibration and a popup only for text messages.

**Comment by qraq** [comment] 2016-08-17 08:13
Same for me, on android 6.0.1. QKSMS version 2.7.1

**Comment by Jrdnkasparek** [comment] 2016-08-17 14:37
@heyforgetit  If you aren't getting notifications for text messages, depending on what version of Android you are running you may need to check "app info" and make sure that notifications are not blocked

If you meant mms notifications then just ignore this

**Comment by frogoscar** [comment] 2016-08-23 14:29
Yes, no notification for MMS received.
But for SMS, yes

**Comment by moezbhatti** [comment] 2016-08-27 07:16
Duplicate of #510, closing this one to merge them

**Closed** 2016-08-27 07:17 UTC
Labels: bug: confirmed repro, duplicate
