### ISSUE TITLE
Sync messages automatically at first launch.

### ISSUE THREAD

**Issue by EgyptianM** [moezbhatti/qksms#1320] opened 2018-09-28 06:28 UTC
### DESCRIPTION
Sync messages automatically when you switch to QKSMS as your default messaging app

### STEPS
1. Install QKSMS for the first time.
2. Press Change to make it your default SMS app.

### EXPECTED
App should sync messages immediately and show them in the list.
 
### OBSERVATIONS
App doesn't sync messages until you sync it manually or restart it.

**Comment by moezbhatti** [comment] 2019-03-06 06:22
This is the intended behaviour. I can't seem to repro this issue - so I'll be closing this until it's re-reported

**Closed by moezbhatti** 2019-03-06 06:22 UTC
