### ISSUE TITLE
Reactions 

### ISSUE THREAD

**Issue by Person0z** [moezbhatti/qksms#1891] opened 2022-09-02 00:11 UTC
So, with the default message from my phone. I get the emoji reactions from iphone users (I can't send but I can see when people send them to me) is it possible in anyways to do that so I don't have a message like

Me: Thanks!
Other person: Liked "Thanks!"

**Comment by xxxxme** [comment] 2022-11-12 15:53
Duplicate of https://github.com/moezbhatti/qksms/issues/1330

**Closed as not planned** 2023-01-16 18:22 UTC
