### ISSUE TITLE
[Feature] IOS `Like` implementation

### ISSUE THREAD

**Issue by Doomsdayrs** [moezbhatti/qksms#1649] opened 2020-09-24 21:59 UTC
### DESCRIPTION
IOS phones seem to be able to "like" a message, which on android reads as `Like "MESSAGE_CONTENT"`

### STEPS
1. Have friend text you with IOS phone
2. Get the like message

### Idea
Parse the message, If it starts with `Like "` then begin the process. 
1. Flag the message to not be displayed
2. Store a DB table linking the `like` message to the message that matches the content of `MESSAGE_CONTENT`
3. Update the liked message with a chip of a :heart: under it

**Comment by dstd** [comment] 2020-12-11 07:57
Unfortunately it's not that straightforward. The content of the message depends on the language settings of sender's device.

**Comment by sm4rk0** [comment] 2020-12-12 03:41
Duplicate of #1330

**Closed** 2020-12-13 04:09 UTC
