### ISSUE TITLE
Crashed when scrolling through search results

### ISSUE THREAD

**Issue by Ravenstencil** [moezbhatti/qksms#13] opened 2015-02-23 06:01 UTC
Searched for the word "test" and it crashed when I scrolled to the bottom of the results.

Approximately 12 conversations were returned.

**Comment by srcreigh** [comment] 2015-03-14 19:49
Can't reproduce this issue. Can you provide any more details? Is it crashing for other queries? Can you tell if there is a pattern for the crashing, i.e. when it matches an MMS message?

**Comment by Ravenstencil** [comment] 2015-03-14 20:41
It crashed on all queries. I was unable to successfully search for any message.

**Comment by Samcfuchs** [comment] 2015-08-18 23:05
Couldn't reproduce on Moto X 2013.

**Comment by moezbhatti** [comment] 2017-10-04 03:23
Should be fixed in QKSMS 3.0

**Closed by moezbhatti** 2017-10-04 03:23 UTC
Labels: bug: needs repro
