### ISSUE TITLE
When writing a text longer than a line, if you keep writing QKSMS hides your text until you pause.

### ISSUE THREAD

**Issue by kyiami** [moezbhatti/qksms#1261] opened 2018-07-24 20:32 UTC
### DESCRIPTION
"Write a message" box does not grow with the amount of text if you keep typing. 

### STEPS
1. Install QKSMS. 
2. Open it up and start writing someone in a SMS (works with MMS too). 
3. Once you write longer than a line, instead of the text box resizing to the amount of text while typing, you have to stop typing and wait for it to come all the way up. 

### EXPECTED
What would be expected is that the "moving down a line" animation plays while writing, and that you don't need to stop to wait for it OR there is no animation and it just skips to the next line. 

### OBSERVATIONS
When writing, the text box does not resize itself if you keep typing - it only does it if you pause typing for a second.

**Comment by moezbhatti** [comment] 2018-07-24 20:33
Duplicate of #1078

**Closed by moezbhatti** 2018-07-24 20:33 UTC
