### ISSUE TITLE
Unable to receive messages after MIUI 13 update.

### ISSUE THREAD

**Issue by jcperil** [moezbhatti/qksms#1868] opened 2022-04-09 13:04 UTC
### DESCRIPTION
After MIUI 13 update, I haven't been able to receive any messages on QKSMS. However, it works fine when the default app is the official (Google) Messages client.

### STEPS
1. Make QKSMS as your default messaging app.
2. Ask a friend to send you a message.
3. No message received.

### EXPECTED
Receive the message.

### OBSERVATIONS
No message received and no notification. The sync between QKSMS and Google Messages isn't working.

**Comment by vixpr** [comment] 2022-04-12 10:30
same.

**Comment by lc-at** [comment] 2022-04-14 12:46
I can confirm that I experienced the same issue.

**Comment by FRAMCHEZ** [comment] 2022-05-29 23:49
Think MIUI 13 with Android 12 was fine, but after last  "security update" lot of problem, and QKSMS not working is one of them. Regards.
MIUI Global 13.0.2 , Android 12 SKQ1.211006.001 , Security Update 2022-04-01

**Comment by XDream8** [comment] 2023-01-27 07:50
This problem seems to be fixed with the latest version

**Comment by jcperil** [comment] 2023-01-29 07:21
It's not fixed for me yet. I receive messages only if the app is open.

I experimented by sending 4 messages from another device. I opened the app only before 2nd and 4th message. The outcome below. I did not receive the 1st and 3rd messages.

<img src="https://user-images.githubusercontent.com/89805719/215311389-c5510c68-b01e-4b6c-8cf0-d54362b9c363.jpg" height="300px"/>

**Comment by XDream8** [comment] 2023-01-29 07:59
Well, then it may be because i disabled battery saver restrictions and enabled auto start

![Screenshot_2023-01-29-10-58-26-544_com miui securitycenter](https://user-images.githubusercontent.com/62709801/215313283-08131ef4-59a8-46ed-aa6f-7ee5149cd95a.jpg)

**Comment by jcperil** [comment] 2023-01-29 08:55
I see. No need to disable batter saver restrictions. I was able to receive messages after enabling `Autostart`.

I would still prefer to receive my messages normally without Autostart workaround.

**Comment by XDream8** [comment] 2023-01-29 09:12
I am fine with this workaround. I don't want to use Google's messages app

**Closed as completed** 2023-02-06 13:55 UTC
