### ISSUE TITLE
"Strip accents" behaviour is unclear, and the user can't tell when it activated

### ISSUE THREAD

**Issue by PaperMountainStudio** [moezbhatti/qksms#1333] opened 2018-10-21 20:44 UTC
When you write SMS in Czech, you use characters like ě or ř. When you use even one, your SMS length is shortened. In textra this is solved by a option in settings - automatically remove diacritics from text if it sends less SMS. By enabling this every ř becomes r and so on. The result is less readable but still understandable.
Is it possible to add such a feature? This is the only thing I missed when coming from textra. I know at least 3 people who would use this app if it had this functionality. Thanks.

**Comment by sm4rk0** [comment] 2018-10-22 07:31
You probably know that there is a "Strip accents" option in Settings, but it can be "On" or "Off". What you propose would be a third state (or another Boolean) and that would be really useful.

**Comment by PaperMountainStudio** [comment] 2018-10-26 20:46
@sm4rk0 Yes, exactly.

**Comment by moezbhatti** [comment] 2018-11-13 13:43
Hey @PaperMountainStudio, sorry for the late response! This is actually the current behavior of the `Strip accents` feature. It's hard to tell, though, because it will store the message locally on the phone with all of the original diacritics

So, in that case, I'm not sure what a third option would offer. Please feel free to re-open and correct me if I'm wrong!

**Comment by sm4rk0** [comment] 2018-11-13 16:20
Indeed...
I never tried this option, so I judged by its description. After a quick test, I can confirm that there are two modes:
1. Strip accents: Off - obvious
2. Strip accents: On - actually doesn't strip the accents unless that's necessary (Auto mode)

@moezbhatti two suggestions:
1. Correct the setting hint so the user knows what to expect
2. Add a way for a user to know when the accent stripping was triggered.
I understand that converting the message body o the fly is not convenient, because for example a user can decide to shorten the message below the limit, but that would still leave the accents stripped.

**Comment by moezbhatti** [comment] 2018-11-13 16:21
@sm4rk0 I agree, it's certainly not clear enough what the user should expect when they enable this setting, and there's no indication for when it has triggered or not. I'll update the issue to reflect the new goal

**Comment by PaperMountainStudio** [comment] 2018-11-13 21:02
@sm4rk0 I didn't propose to strip accents on the fly, I think. But when I look at my text again, it might seem like that. Anyway,
I didn't know that "strip accent" option actually did this.
I agree that it is not clear enough, so my proposal is this: Clicking on "strip accent" will show a menu with 3 radio buttons:
1. Off
2. Smart
3. On
Thanks.

**Comment by moezbhatti** [comment] 2019-12-16 15:16
Closing this in favour of #1149

**Closed by moezbhatti** 2019-12-16 15:16 UTC
Labels: enhancement
