### ISSUE TITLE
Contact Names Don't Refresh

### ISSUE THREAD

**Issue by ChillMasterT** [moezbhatti/qksms#902] opened 2018-02-24 03:02 UTC
### Bug Description
After adding a contact or changing their name it does not refresh/update in QKSMS, even after a force stop. This means that if someone texts you for the first time and you add them to your contacts, you are stuck seeing their phone number instead of their name. Behavior is the same for both SMS and MMS messages.

### Device Details
* Device: ONEPLUS A3000
* Operating System: OxygenOS 5.0.1 (Android 8.0.0 Oreo)
* QKSMS Version: 3.0 Beta 2
* Oneplus Contacts Version 2.1.0.171211210621.bc6c399

**Comment by moezbhatti** [comment] 2018-02-24 04:32
Confirmed.

A temporary workaround is to open the compose message screen, this should trigger a refresh of the contacts

**Comment by ChillMasterT** [comment] 2018-02-24 04:36
Ok, thanks for the info.

**Comment by moezbhatti** [comment] 2018-03-13 00:49
Fixed in 7e2b4e91b424487a2fa8c6dbadd6583c11321143

**Comment by moezbhatti** [comment] 2018-03-13 09:15
Duplicate of #329

**Closed by moezbhatti** 2018-03-13 09:15 UTC
Labels: Bug
