### ISSUE TITLE
Copy button for OTP (Authentication Code)

### ISSUE THREAD

**Issue by sstarlung** [moezbhatti/qksms#1513] opened 2019-10-18 03:33 UTC
Feature:
OTP sms is more and more popular, especially for on-line pay/remittance. How about recognition verification code and popup a copy button like app "SMS Plus"?

Thank you.

**Comment by moezbhatti** [comment] 2019-10-31 05:36
Duplicate of #881

**Closed by moezbhatti** 2019-10-31 05:36 UTC
