### ISSUE TITLE
Do the messages used in this app get sent to Google's servers?

### ISSUE THREAD

**Issue by markcellus** [moezbhatti/qksms#1873] opened 2022-05-10 02:03 UTC
This is more of a question than an issue. But it is very odd.

There have been multiple times where I've mentioned something only in a text message in this app and I immediately start seeing youtube recommendations related to what I've mentioned. I've reproduced this once by using a very esoteric term that I've never spoken out loud with success. 

I realize there could possibly be some other explanation but I'd just like to make sure. 

Can you confirm whether or not messages in this app get sent to any third parties? Particularly Google?

Thank you for any information you can provide.

**Comment by markcellus** [comment] 2022-05-10 02:07
If not, I've also noticed that the app can sync with Android's SMS database. Could it be possible that that database is sending messages to Google?

**Comment by MXC48-zz** [comment] 2022-06-11 11:26
> If not, I've also noticed that the app can sync with Android's SMS database. Could it be possible that that database is sending messages to Google?

it is possible depending on whether you are on a degoogled android or not, otherwise the recipient may be the cause.
if Google has spotted you, it can track you like this through your recipient.

**Comment by e-t-l** [comment] 2023-01-16 17:01
Also, if the Google app (or Assistant, or Google Calendar, or if you're on GrapheneOS the Google Play/Services/Framework app, etc...) have been granted the Read/Write SMS permission (or even Notifications Access permission) then Google is likely scraping all your messages. Unfortunately nothing can be done about this within the QKSMS app. 

**To answer your original question, do messages get sent to Google's servers: No. (not by QKSMS, at least). Recommend closing this issue.**

**Closed as completed** 2023-01-16 17:51 UTC
