### ISSUE TITLE
3.9.0 slow when performing certain actions

### ISSUE THREAD

**Issue by d5xtgr** [moezbhatti/qksms#1712] opened 2021-01-07 04:48 UTC
### DESCRIPTION
Some actions cause the app to temporarily lock up after upgrading to version 3.9.0 from 3.8.1.

### STEPS
1. Open an existing conversation
2. Draft a reply
3. Return to top level
4. Wait for draft to appear
5. Enter another conversation

### EXPECTED
Steps 4 and 5 should occur without significant delay.

### OBSERVATIONS
Step 4: the text does not update to reflect the draft until about seven seconds have passed.
Step 5: the app is unresponsive for about five seconds, and then the screen goes black for a second or two before the conversation loads.

Similar freezes occur when opening the app from the new-message notification.

Timings on Essential PH-1 running Lineage 14.1 without Google apps.

**Comment by peylight** [comment] 2021-01-07 14:27
I have the same problem with android 8.1.0
Version 3.9.0 totally unusable!

**Comment by moezbhatti** [comment] 2021-01-07 17:02
Thanks for the heads up, I've had a few reports of this. Will look into it asap

@peylight what phone are you running the app on?

**Comment by Psychoticpotato** [comment] 2021-01-07 18:27
I am running into the same issue.
Oneplus 3T
Android 8.1.0

**Comment by d5xtgr** [comment] 2021-01-08 03:15
I've since noticed delays occurring when sending a message: several seconds elapse between pressing enter and the appearance of the message with the "Sending..." status.

Also, when opening a conversation after receiving a text, tapping a notification causes a lockup, but dismissing the notification and opening the app from the launcher works.  However, even when opened from the launcher, it takes several seconds for the new message to display in either the main view or the conversation.

It might be that any action involving querying the database is slow if the database has been updated since it was last queried.

**Comment by Vollblut** [comment] 2021-01-08 07:41
I have similar issues. Ive tried to temporarily switch to Tibur's 'simple SMS' app but encountered similar problems. Failures to send SMS and extremely sluggish database updates/syncs. Presumably an issue with androids SMS handling?

**Comment by xkollar** [comment] 2021-01-08 22:24
Android 10, QKSMS 3.9.0, downgrade to 3.8.1 helped.

**Comment by xkollar** [comment] 2021-01-08 23:13
Playing with it more: downgrade in f-droid fails (maybe not related), so I had to uninstall and install again. I tried to upgrade again, and funnily enough, first opening of conversation was okay, but any subsequent made application freeze, and after couple of seconds screen goes black.

Also I tried to uninstall and install newest version (and re-import all messages with "set as default" process), and that had same result as upgrade (was curious whether upgrade path is involved).

**Comment by moezbhatti** [comment] 2021-01-08 23:46
@Vollblut and @xkollar, can you confirm what devices you're running?

**Comment by d5xtgr** [comment] 2021-01-08 23:48
> Ive tried to temporarily switch to Tibur's 'simple SMS' app but encountered similar problems. Failures to send SMS and extremely sluggish database updates/syncs. Presumably an issue with androids SMS handling?

The stock messaging app on Lineage works fine, so I don't think this is correct.

> Also I tried to uninstall and install newest version (and re-import all messages with "set as default" process), and that had same result as upgrade (was curious whether upgrade path is involved).

That's useful, thanks!

**Comment by Vollblut** [comment] 2021-01-09 00:00
> @Vollblut and @xkollar, can you confirm what devices you're running?
Oneplus 3T with newest LineageOS. 

> The stock messaging app on Lineage works fine, so I don't think this is correct.
I always presumed that the stock SMS app is the source which third party apps sync against. 
Im using that one btw, it indeed works as expected.

**Comment by xkollar** [comment] 2021-01-09 00:37
Nokia 3.1, Android One (stock), Android version 10.

**Comment by helion** [comment] 2021-01-09 02:48
The top report is spot on for what I'm experiencing since the update as well. Moto G5 Plus running stock Android 8.1.0

**Comment by xkollar** [comment] 2021-01-09 11:53
I wonder whether this might be related to #1708, as I have blocked lots of Google stuff on my phone, so maybe that might be causing an issue? What about other people experiencing this?

**Comment by moezbhatti** [comment] 2021-01-09 16:23
@xkollar I don't think it should be related to #1708, since any Google stuff is only related to billing and crash reporting

I'll be investigating this today, and I'll post a test build here once I have something. If anyone will be around to test it out for me, that would be fantastic

**Comment by NovaViper** [comment] 2021-01-09 19:39
Same issue here on Samsung S9 Android 10

**Comment by moezbhatti** [comment] 2021-01-11 03:29
alright, I think I might have tracked down the problem. I've attached two builds here - one from before the suspected problem was introduced, and one from after. if the issue is what I think it is, then `QKSMS-test-1.apk` should work fine, and `QKSMS-test-2.apk` should behave just like 3.9

could someone who is experiencing the problem please test these out and let me know if my suspicion is correct?

[QKSMS-tests.zip](https://github.com/moezbhatti/qksms/files/5793901/QKSMS-tests.zip)

**Comment by xkollar** [comment] 2021-01-11 08:54
Will do through the day :+1:

**Comment by xkollar** [comment] 2021-01-11 14:47
I confirm that `QKSMS-test-1.apk` works fine and `QKSMS-test-2.apk` indeed exhibits same behavior as 3.9.0.

**Comment by NovaViper** [comment] 2021-01-11 15:37
Can confirm that `QKSMS-test-1.apk` works aswell

**Comment by moezbhatti** [comment] 2021-01-11 16:13
@NovaViper can you confirm that `QKSMS-test-2.apk` is problematic?

**Comment by NovaViper** [comment] 2021-01-11 17:42
Oh sorry! Yeah, the test 2 apk is buggy as it was in 3.9.0

**Comment by moezbhatti** [comment] 2021-01-12 01:05
Fantastic, thanks for checking! And just to confirm, were you experiencing pretty much the same thing as what @d5xtgr described at the top of this issue? Or was it some other badness

@xkollar @NovaViper

**Comment by NovaViper** [comment] 2021-01-12 01:20
At least for me, it was just overall lagginess when I had 3.9.0, the app would just completely lock up if I sent a MMS message to anyone

**Comment by xkollar** [comment] 2021-01-12 09:22
Yes, even though I didn't need to do all the steps they described. For me reproducer was just enter conversation, exit (back to conversation list), and re-enter the same conversation, at which point it would be completely unusable (eventually it would render, but that would be tens of seconds, after screen going black (not locks screen, just turn black even though still on)).

**Comment by xkollar** [comment] 2021-01-12 18:12
@d5xtgr seems to describe more issues in his second post that are not necessarily related (I had similar behavior even on 3.8.1 (sometimes it taking long time before message appearing in conversation after being sent)).

**Comment by NovaViper** [comment] 2021-01-12 18:15
@xkollar I had the same issues with messages taking a long time to appear in both versions too

**Comment by Roy-Orbison** [comment] 2021-01-13 02:32
> Playing with it more: downgrade in f-droid fails (maybe not related), so I had to uninstall and install again. I tried to upgrade again, and funnily enough, first opening of conversation was okay, but any subsequent made application freeze, and after couple of seconds screen goes black.

I was able to reproduce this same 'first-run' speed-up that @xkollar saw by simply closing the app, going to its _App Info_ system settings screen, and clearing its cache (but not its storage). The next time I ran it, it was snappy again (opening a very long conversation), but subsequent navigation to other conversations and back to the long one slowed down. It's like it's having more trouble using cached than direct data.

I also saw the delay when sending that @d5xtgr reported.

**Comment by alekksander** [comment] 2021-01-14 07:43
Had the same issue. installed (simple) SMS messagner and it fixed the issue. Now qksms is default again and is working as fast as before.

**Comment by slecache** [comment] 2021-01-14 08:30
> 
> 
> @Vollblut and @xkollar, can you confirm what devices you're running?

I have the same issue on OnePlus 6T with /e/OS

**Comment by Klev42** [comment] 2021-01-17 21:28
Hello!
Sadly I have the same issue on a Fairphone 3 with Android 10. (I did not tried the linked builds for now)

As I was reading this thread, I was thinking that it could be a good idea to temporary withdraw the 3.9.0 version from Fdroid and/or Playstore? As @xkollar said, it is not possible to retrograde on fdroid, and on my side QKSMS does not respond for at least 30 seconds. I have to use (for the first time in my life) Google Messages. If the bug concern a variety of android versions and devices, QKSMS could lose a part of its user base. But I am only suggesting!

Thank you for your work on this app and good luck to fix this issue

**Comment by slecache** [comment] 2021-01-22 13:22
> As I was reading this thread, I was thinking that it could be a good idea to temporary withdraw the 3.9.0 version from Fdroid and/or Playstore? As @xkollar said, it is not possible to retrograde on fdroid, and on my side QKSMS does not respond up to at least 30 seconds when the bug occurs when opening a picture shared in the conversation. I have to use (for the first time in my life) Google Messages. If the bug concern a variety of android versions and devices, QKSMS could lose a part of its user base. But I am only suggesting!
Retrograde on fdroid no longer works but you can uninstall QKSMS 3.9.0 and then after reinstall the 3.8.1 version.

**Comment by Erlotinib** [comment] 2021-01-25 17:18
Hello,

On my oneplus 3T with lineage 17.1, I confirm that QKSMS-test-1.apk works fine and QKSMS-test-2.apk exhibits the same behavior as 3.9.0 (wait of dozen seconds to render a conversation or a new message)

**Comment by moezbhatti** [comment] 2021-02-02 04:02
Hey folks, apologies for the delay here! If anyone has a chance, could you test this build and let me know if it resolves the performance you're seeing in the 3.9.0 build?

[QKSMS-v3.9.1-prerelease-noAnalytics-release.apk.zip](https://github.com/moezbhatti/qksms/files/5908538/QKSMS-v3.9.1-prerelease-noAnalytics-release.apk.zip)

**Comment by Erlotinib** [comment] 2021-02-02 07:40
Hello,

After some quick tests, I can’t reproduce the issue with the build above (3.9.1 prerelease), I will continue to use it but seems fixed for me.

Thanks

**Comment by xkollar** [comment] 2021-02-02 14:47
Will check tonight :+1:

**Comment by moezbhatti** [comment] 2021-02-03 00:08
Awesome. If I can get a few more 👍  on this build, then I can feel comfortable going ahead and pushing out the fix tonight

**Comment by Klev42** [comment] 2021-02-03 09:46
Hello,
Thank you for your efforts!
Sadly it seems that the `QKSMS-v3.9.1-prerelease-noAnalytics-release.apk` build doesn't fix the bug on my side. Like in the 3.9.0 version, opening a conversation and then another one leads to a delay of at least 6 seconds of nothing (display doesn't change) followed by the app turning black for one minute. After that the conversation opens.
I did not try to reset the application settings. I did not try `QKSMS-test-1.apk`.

**Comment by xkollar** [comment] 2021-02-03 09:55
Tested even with conversations with 30k+ messages in it and 3.9.1-prerelase works for me without an issue.
Tested also on Samsung m31 (where QKSMS-test-1.apk worked and QKSMS-test-2.apk exhibited the bug also.)

**Comment by xkollar** [comment] 2021-02-03 10:00
One more thing I tried was to back up my messages, delete all conversation and restore (Yeah, I lost mms, but that is life I guess, as app states, hopefully coming soon with also backing up scheduled messages :upside_down_face:). Still QKSMS-test-2.apk was exhibiting the issue.

**Comment by moezbhatti** [comment] 2021-02-03 13:16
@Klev42 would it be possible for you to test out `QKSMS-test-1.apk` and `QKSMS-test-2.apk` and see if your experience is consistent with the others in this thread? 1 should not exhibit the issue, while 2 should

**Comment by r0xsh** [comment] 2021-02-03 19:39
`QKSMS-v3.9.1-prerelease-noAnalytics-release.apk` tested on a Honor 5X with LineageOS 7.1.2 on it. I couldn't reproduce the slowness. I think it's fixed :)
Thanks !

**Comment by Klev42** [comment] 2021-02-03 19:50
@moezbhatti Okay :smile:

1. I begin by uninstalling `QKSMS-v3.9.1-prerelease-noAnalytics-release.apk` that I have previously installed.
2. I install `QKSMS-test-2.apk`. It behaves slowly like 3.9.0 (as intended) and my previous test of `QKSMS-v3.9.1-prerelease-noAnalytics-release.apk`.
3. I uninstall `QKSMS-test-2.apk` and install `QKSMS-test-1.apk`. This last one works like a charm and there is no problem with it <3
4. After that I uninstall `QKSMS-test-1.apk` and I install again  `QKSMS-v3.9.1-prerelease-noAnalytics-release.apk`: and this time the app works like a charm too.

I had not uninstalled the app before. So I suppose that clearing the app data when I unninstalled QKSMS in step 1 changed something. So maybe the app data can inhibit/prevent the fix in `QKSMS-v3.9.1-prerelease-noAnalytics-release.apk` that seems to works when app data is cleared.

Thanks for the fix!

**Comment by moezbhatti** [comment] 2021-02-03 19:58
That's excellent news, thanks everyone! I'll roll out 3.9.1 later this evening :)

**Comment by Klev42** [comment] 2021-02-04 10:08
Sorry to reopen this issue, but today slow behavior is coming back. Freezes and black-screens when interacting with conversations. I think that the behavior is the same as before. Tell me if I can do something that can help to understand what happens.

**Comment by moezbhatti** [comment] 2021-02-04 16:28
@Klev42 Can you open the settings and scroll to the bottom and let me know what version you're on?

**Comment by Klev42** [comment] 2021-02-04 17:22
Hello @moezbhatti
It shows 3.9.0. I reinstalled  `QKSMS-v3.9.1-prerelease-noAnalytics-release.apk` and now it shows 3.9.1. I don't know what I have done to mess that up. So thank you for asking and probably PEBCAK on my side.

**Comment by moezbhatti** [comment] 2021-02-04 22:43
Got it, thanks for checking!

**Comment by moezbhatti** [comment] 2021-02-05 05:32
Hey folks, sorry for all the back and forth. Looks like the change I made to fix the problem here ended up breaking the Google Play release

I was able to repro the new crash and fix it, but unfortunately I'm not able to reproduce the lag issue on own device, so I need some help testing this new build to make sure I haven't reintroduced the lag problem. Would someone mind testing this for me and letting me know if the lag is back or not?

cc @Klev42 @r0xsh @xkollar @Erlotinib 

Thanks so much!

[QKSMS-v3.9.2-prerelease.apk.zip](https://github.com/moezbhatti/qksms/files/5930333/QKSMS-v3.9.2-prerelease.apk.zip)

**Comment by Klev42** [comment] 2021-02-05 07:02
Hello
Sadly `QKSMS-v3.9.2-prerelease.apk` reintroduces the issue on my device. Even when removing app data, even when uninstalling then reinstalling this version (if that makes a difference)
(Also: for my previous message it seems that my phone decided to automatically downgrade QKSMS daily. I found [this](https://stackoverflow.com/questions/43444492/android-app-automatically-downgrade-version) on that matter but I don't think that will help)

**Comment by r0xsh** [comment] 2021-02-05 13:36
I just quickly tried the `3.9.2` at work, thé slowness are back :/

**Comment by moezbhatti** [comment] 2021-02-05 14:36
Okay, thanks for checking. I'll keep looking for a fix

> (Also: explaining my previous message, it seems that my phone decided to automatically downgrade QKSMS daily. I found this on that matter but I don't think that will help)

The prerelease versions I've been uploading don't bump the version number, so that would be why. Once 3.9.1 is on F-Droid, you can download it from there and you won't be reverted anymore

**Comment by moezbhatti** [comment] 2021-02-05 19:18
If I haven't already asked for too much – I've got two more potential fixes I was hoping you could test for me

Note that after you try `prerelease-3`, you'll need to uninstall before you revert back

[QKSMS-v3.9.2-prerelease-2.apk.zip](https://github.com/moezbhatti/qksms/files/5934772/QKSMS-v3.9.2-prerelease-2.apk.zip)
[QKSMS-v3.9.2-prerelease-3.apk.zip](https://github.com/moezbhatti/qksms/files/5934771/QKSMS-v3.9.2-prerelease-3.apk.zip)

**Comment by Klev42** [comment] 2021-02-05 21:00
Pretty glad to help 🙂
On my side:
- `prerelease-2` have the massive slowness issue on my side.
- `prerelease-3` seems a little bit laggy compared to the 3.9.1 that worked like a charm or to what it was before 3.9.0. In other words, the issue I that not as bad as what we had before, but the app fluidity is considerably reduced. I will say that this version needs one second to open a conversation

**Comment by moezbhatti** [comment] 2021-02-05 22:10
Thank you so much @Klev42!

Here's the next one. This one involves the changes from `prerelease-3`, but I think it should be a little bit faster. There will likely be some crashes in random places throughout the app - if you spot any let me know and I'll make sure those get patched up before the actual release. But what I'm mostly looking for here is whether or not it's any better than `prerelease-3`, so give it a try and let me know!

After you install it and test, I would also like you to restart the app once or twice and then try again and see if that makes any further improvement

[QKSMS-v3.9.2-prerelease-4.apk.zip](https://github.com/moezbhatti/qksms/files/5935611/QKSMS-v3.9.2-prerelease-4.apk.zip)

**Comment by moezbhatti** [comment] 2021-02-06 00:31
Reopening, since the "solution" ended up breaking the build for Google Play users, so we still need to find a solution

**Comment by Klev42** [comment] 2021-02-06 11:15
Hello @moezbhatti
I tried to compare `3.9.2-prerelease-4` to `3.9.2-prerelease-3`. At first I thought that `prerelease-4` was quicker but more precise observations it seems that it's not the case. Even with a fresh reinstall.

To be precise, when opening the same conversation, `prerelease-4` and `prerelease-3` takes between ~2 to ~5 seconds to open. The delay is 2 seconds at the first conversation opening, and then reopening the same conversation makes the delay longer. Swipe up the app in the recent apps view (to ~close it) "resets" this delay to 2 seconds.

I returned to `3.9.1-prerelease` to compare: with 3.9.1 the delay is too short for me to be able to time it, so less than a second. I humbly think that this fluidity is clearly what we should aim

Bugs and remarks about `3.9.2-prerelease-4`:
- Opening a picture from the conversation crash the app. But opening a picture from the overflow menu who lists all the pics works
- Tying to change contact color from this overflow menu crashes the app
- Forcing the app to close and then reopen it seems to not have any impact on slowness. Tell me if you wanted a more specific test on that matter, I only tried it twice.

**Comment by Erlotinib** [comment] 2021-02-06 11:52
Hi,

I'm testing 3.9.2-prerelease-4 (Oneplus 3T, lineageos 17.1, microg) and at first it seems a bit slower than 3.9.1-prerelease but not to the same extent than 3.9.0. It's more like an half-second to display whereas in 3.8 (and 3.9.1-prerelease) it was instantaneous. 

But on successive opening of the same conversation, it becomes slower and slower, at about the twentieth repetition (just, opening and closing a conversation), it needs >2 seconds before displaying.

I can also confirm the above crashes with image in conversation and changing contact color.

regards

**Comment by moezbhatti** [comment] 2021-02-06 15:58
Got it, thanks for confirming

When you say it's slow to open - which one of these scenarios better describes what's happening?

1. The conversation screen appears and shows the contact name and correct colour right away, but the messages don't appear for a couple seconds
2. The conversation screen app comes up right away, but it doesn't show any of the correct content for a couple seconds
3. The conversation screen doesn't even appear for a few seconds after clicking the conversation

**Comment by Klev42** [comment] 2021-02-06 16:32
When it's the first conversation opening, I will say 1.
But after more than one openings of the same conversation, the contact name doesn't appears right away. However the color is here and correct. I will put screenshots bellow for this to be more clear
Before, with 3.9.0, it was 3. The screen often even turned black.

Numbered screenshots are hosted [there](https://drive.google.com/drive/folders/1oNe0V4TB-NOPZZnbmYpy63D9Xec4Guwv?usp=sharing). Profiles pictures and conversation content where there at screenshot 3, I removed them for anonymization.
First conversation opening: screenshot 2 then 3
Second and following openings: screenshot 1, 2 then 3

**Comment by Erlotinib** [comment] 2021-02-06 18:24
I've got the same behavior than Klev42.

**Comment by moezbhatti** [comment] 2021-02-06 21:20
Gotcha, thanks. I'll continue looking for a fix

**Comment by moezbhatti** [comment] 2021-02-06 23:35
Okay, I don't want to count my chickens before they've hatched, but I think I might have something here. Mind giving this one when you've got a chance?
[QKSMS-v3.9.2-prerelease-5.apk.zip](https://github.com/moezbhatti/qksms/files/5937866/QKSMS-v3.9.2-prerelease-5.apk.zip)


🤞

**Comment by Klev42** [comment] 2021-02-07 09:08
Hello
Sadly, on my side, `3.9.2-prerelease-5` makes the app as slower as in the
initial 3.9.0 release. With black screen when opening another conversation
or freezing for interactions.

>

**Comment by Erlotinib** [comment] 2021-02-07 10:24
Hi,

I'm in the same boat:

with 3.9.2-prerelease-5, first interaction is normal. Subsequents openings of conversation are very slow and it becomes nearly unusable after a while.

The behavior is a bit different in that qksms freeze when the conversation is selected ; then after 2-3 sec, the screen becomes black, then after a dozen of seconds the conversation appears. 

Access to a conversation directly from homepage (e.g. to read/answer a new sms) leads to a blank screen for a long time.

**Comment by moezbhatti** [comment] 2021-02-07 15:26
Yikes. Okay, thanks guys. The search goes on

**Comment by moezbhatti** [comment] 2021-02-07 19:11
Okay, I'm fairly confident now that I have a fix. New build incoming in ~30 mins. If someone's around to test it out for me, that would be massively appreciated!

**Comment by moezbhatti** [comment] 2021-02-07 19:48
Alright, here we go:

[QKSMS-v3.9.2-prerelease-6.apk.zip](https://github.com/moezbhatti/qksms/files/5939841/QKSMS-v3.9.2-prerelease-6.apk.zip)

**Comment by Klev42** [comment] 2021-02-07 19:56
Hello!
`prerelease-6` works like a charm on Fairphone 3! No lag to open a conversation, no crash when opening a picture, no crash when changing contact color.

**Comment by moezbhatti** [comment] 2021-02-07 20:06
Amazing. Thank you so much for your help! I couldn't repro the issue on any of my test devices, so I was mostly shooting in the dark here. If I didn't have everyone's help with testing, this would have taken me weeks to figure out

**Comment by moezbhatti** [comment] 2021-02-07 20:30
Fixed in ff4170af324eff7446f6ae41800c245f9fef1e0d...062adb76ac89d57bb73af75244f282a1a5dfa3d9

**Closed by moezbhatti** 2021-02-07 20:30 UTC

**Comment by Erlotinib** [comment] 2021-02-07 21:26
Hi,

I confirm on my oneplus 3T (lineageos 17.1, microg) , all the above bugs seems fixed.

thanks
regards

**Comment by Klev42** [comment] 2021-02-08 16:34
Hello,
Today the app is crashing systematically when started.
Somehow, SMS and MMS that people said they sent me today were not notified and seem to be lost from the SMS/MMS database of android. I did not saw them today and they do not appear in Google Messages.

It's impossible to check the version in app − because of application crashes. However app information shows 3.9.1.

Is there someone who faced the same crashes with the last version? @Erlotinib ?

Sadly, since my work implies that I use SMS to receive appointments requests, I can not continue to beta test. I knew the risks :)

**Comment by moezbhatti** [comment] 2021-02-08 19:06
`3.9.1` is broken build that we spent the day trying to fix yesterday - you'll need to upgrade to `3.9.2`:)

**Comment by Klev42** [comment] 2021-02-08 19:16
You are right. But I had upgraded to this last one. My phone retrograded
again I suppose… 😁

Le lun. 8 févr. 2021 à 20:07, Moez Bhatti <notifications@github.com> a
écrit :

**Comment by moezbhatti** [comment] 2021-02-08 19:18
You might have been on the prerelease, which didn't actually include a version bump. Once you update to the official `3.9.2` build, it should be impossible to get reverted (save for a manual uninstall)

**Comment by Erlotinib** [comment] 2021-02-08 20:29
Hello,

With prerelease 6, I didn't get any crash or slowness today. (I don't have google play on my phone, only fdroid and only manual update)
