### ISSUE TITLE
Search for messages from the search bar

### ISSUE THREAD

**Issue by justiceo** [moezbhatti/qksms#1345] opened 2018-11-21 02:39 UTC
### DESCRIPTION
Currently a query in the search bar only filters the messages by contact name (or conversation name), it would be nice to find messages by querying for it.

### STEPS
1. Type a query that should match a message you sent or received but not someone's name, e.g. "hey!"
2. A noticed is displayed "Your conversations will appear here"

### EXPECTED
It returns conversations with messages that match the query.

### OBSERVATIONS
A notice is displayed. No results returned.

**Comment by prg318** [comment] 2019-08-13 01:16
I'm not able to reproduce all of this - but I am able to reproduce this in group chats and outgoing messages.

I can't reproduce this with incoming, non-group messages.  I opened a related issue here https://github.com/moezbhatti/qksms/issues/1471

**Comment by moezbhatti** [comment] 2019-08-13 08:43
Can't repro this myself either, but I can confirm #1471. Closing this in favour of that one

**Closed by moezbhatti** 2019-08-13 08:43 UTC
