### ISSUE TITLE
Delete in Notification

### ISSUE THREAD

**Issue by danielearrighi** [moezbhatti/qksms#697] opened 2017-01-16 16:04 UTC
Hello,
It would be possible to add a "DELETE" button in the notification instead of "Mark as read" or "Open".
Thank you!

**Comment by woj-tek** [comment] 2017-01-17 11:56
my 5c - only as an option...

**Comment by sm4rk0** [comment] 2017-01-19 14:37
Duplicate of #263 
Please search the existing issues before opening new one.

**Closed** 2017-01-19 17:12 UTC
Labels: duplicate
